translate portuguese strings:
    old "Self-voicing disabled."
    new "Narração assistiva desabilitada."
    old "Clipboard voicing enabled. "
    new "Narração da área de transferência habilitada. "
    old "Self-voicing enabled. "
    new "Narração assistiva habilitada. "
    old "Font Override"
    new "Substituição de Fonte"
    old "Default"
    new "Padrão"
    old "DejaVu Sans"
    new "DejaVu Sans"
    old "Opendyslexic"
    new "Opendyslexic"
    old "Text Size Scaling"
    new "Escala do Tamanho do Texto"
    old "Reset"
    new "Resetar"
    old "Line Spacing Scaling"
    new "Escala do Espaçamento entre Linhas"
    old "High Contrast Text"
    new "Texto de Alto Contraste"
    old "Enable"
    new "Habilitar"
    old "Self-Voicing"
    new "Narração Assistiva"
    old "Off"
    new "Desabilitado"
    old "Text-to-speech"
    new "Texto para Fala"
    old "Clipboard"
    new "Área de Transferência"
    old "Debug"
    new "Depurar"
    old "Self-Voicing Volume Drop"
    new "Redução de Volume da Narração Assistiva"
    old "The options on this menu are intended to improve accessibility. They may not work with all games, and some combinations of options may render the game unplayable. This is not an issue with the game or engine. For the best results when changing fonts, try to keep the text size the same as it originally was."
    new "As opções nesse menu visam melhorar a accessibilidade. Elas não vão funcionar com todos os jogos, e algumas combinações de opções podem deixar o game injogável. Isso não é um problema com o jogo ou a engine. Para melhores resultados mudando fontes, tente manter o tamanho do texto igual ao que era originalmente."
    old "{#weekday}Monday"
    new "{#weekday}Segunda"
    old "{#weekday}Tuesday"
    new "{#weekday}Terça"
    old "{#weekday}Wednesday"
    new "{#weekday}Quarta"
    old "{#weekday}Thursday"
    new "{#weekday}Quinta"
    old "{#weekday}Friday"
    new "{#weekday}Sexta"
    old "{#weekday}Saturday"
    new "{#weekday}Sábado"
    old "{#weekday}Sunday"
    new "{#weekday}Domingo"
    old "{#weekday_short}Mon"
    new "{#weekday_short}Seg"
    old "{#weekday_short}Tue"
    new "{#weekday_short}Ter"
    old "{#weekday_short}Wed"
    new "{#weekday_short}Qua"
    old "{#weekday_short}Thu"
    new "{#weekday_short}Qui"
    old "{#weekday_short}Fri"
    new "{#weekday_short}Sex"
    old "{#weekday_short}Sat"
    new "{#weekday_short}Sáb"
    old "{#weekday_short}Sun"
    new "{#weekday_short}Dom"
    old "{#month}January"
    new "{#month}Janeiro"
    old "{#month}February"
    new "{#month}Fevereiro"
    old "{#month}March"
    new "{#month}Março"
    old "{#month}April"
    new "{#month}Abril"
    old "{#month}May"
    new "{#month}Maio"
    old "{#month}June"
    new "{#month}Junho"
    old "{#month}July"
    new "{#month}Julho"
    old "{#month}August"
    new "{#month}Agosto"
    old "{#month}September"
    new "{#month}Setembro"
    old "{#month}October"
    new "{#month}Outubro"
    old "{#month}November"
    new "{#month}Novembro"
    old "{#month}December"
    new "{#month}Dezembro"
    old "{#month_short}Jan"
    new "{#month_short}Jan"
    old "{#month_short}Feb"
    new "{#month_short}Fev"
    old "{#month_short}Mar"
    new "{#month_short}Mar"
    old "{#month_short}Apr"
    new "{#month_short}Abr"
    old "{#month_short}May"
    new "{#month_short}Mai"
    old "{#month_short}Jun"
    new "{#month_short}Jun"
    old "{#month_short}Jul"
    new "{#month_short}Jul"
    old "{#month_short}Aug"
    new "{#month_short}Ago"
    old "{#month_short}Sep"
    new "{#month_short}Set"
    old "{#month_short}Oct"
    new "{#month_short}Out"
    old "{#month_short}Nov"
    new "{#month_short}Nov"
    old "{#month_short}Dec"
    new "{#month_short}Dez"
    old "%b %d, %H:%M"
    new "%d de %b, %H:%M"
    old "Save slot %s: [text]"
    new "Salvar no slot %s: [text]"
    old "Load slot %s: [text]"
    new "Carregar slot %s: [text]"
    old "Delete slot [text]"
    new "Deletar slot [text]"
    old "File page auto"
    new "Página do arquivo (s. auto)"
    old "File page quick"
    new "Página do arquivo (s. rápido)"
    old "File page [text]"
    new "Página [text] do arquivo"
    old "Next file page."
    new "Página seguinte do arquivo."
    old "Previous file page."
    new "Página anterior do arquivo."
    old "Quick save complete."
    new "Salvamento rápido concluído."
    old "Quick save."
    new "Salvamento rápido."
    old "Quick load."
    new "Carregamento rápido."
    old "Language [text]"
    new "Idioma [text]"
    old "Open [text] directory."
    new "Abrir diretório [text]."
    old "Are you sure?"
    new "Você tem certeza?"
    old "Are you sure you want to delete this save?"
    new "Você tem certeza que deseja deletar este save?"
    old "Are you sure you want to overwrite your save?"
    new "Você tem certeza que deseja sobrescrever este save?"
    old "Loading will lose unsaved progress.\nAre you sure you want to do this?"
    new "Ao carregar, qualquer progresso não salvo será perdido.\nVocê tem certeza que deseja fazer isso?"
    old "Are you sure you want to quit?"
    new "Você tem certeza que deseja sair?"
    old "Are you sure you want to return to the main menu?\nThis will lose unsaved progress."
    new "Você tem certeza que deseja voltar para o menu principal?\nQualquer progresso não salvo será perdido."
    old "Are you sure you want to end the replay?"
    new "Você tem certeza que deseja encerrar o replay?"
    old "Are you sure you want to begin skipping?"
    new "Você tem certeza que deseja começar a pular o diálogo?"
    old "Are you sure you want to skip to the next choice?"
    new "Você tem certeza que deseja pular o diálogo até a próxima escolha?"
    old "Are you sure you want to skip unseen dialogue to the next choice?"
    new "Você tem certeza que deseja pular o diálogo ainda não visto até a próxima escolha?"
    old "This save was created on a different device. Maliciously constructed save files can harm your computer. Do you trust this save's creator and everyone who could have changed the file?"
    new "Este save foi criado em um outro dispositivo. Arquivos de save maliciosos podem colocar seu computador em risco. O criador do save e qualquer um que tenha modificado este arquivo são confiáveis?"
    old "Do you trust the device the save was created on? You should only choose yes if you are the device's sole user."
    new "O dispositivo que criou o save é confiável? Só escolha sim se você for o único usuário deste dispositivo."
    old "Failed to save screenshot as %s."
    new "Falha ao salvar captura de tela em %s."
    old "Saved screenshot as %s."
    new "Captura de tela salva em %s."
    old "Skip Mode"
    new "Modo de Pulo de Diálogo"
    old "This program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license}here{/a}."
    new "Este programa contém software livre sob diferentes licenças, incluindo a Licença MIT e a GNU LGPL. A lista completa dos softwares, incluindo links para o código fonte completo, pode ser encontrado {a=https://www.renpy.org/l/license}aqui{/a}."
    old "Clipboard voicing enabled. Press 'shift+C' to disable."
    new "Narração da área de transferência habilitada. Pressione 'Shift+C' para desabilitar."
    old "Self-voicing would say \"[renpy.display.tts.last]\". Press 'alt+shift+V' to disable."
    new "A narração assistiva diria \"[renpy.display.tts.last]\". Pressione 'Alt+Shift+V' para desabilitar."
    old "Self-voicing enabled. Press 'v' to disable."
    new "Narração assistiva habilitada. Pressione 'V' para desabilitar."
    old "Renderer"
    new "Renderizador"
    old "Automatically Choose"
    new "Escolher Automaticamente"
    old "Force GL Renderer"
    new "Forçar Renderizador GL"
    old "Force ANGLE Renderer"
    new "Forçar Renderizador ANGLE"
    old "Force GLES Renderer"
    new "Forçar Renderizador GLES"
    old "Force GL2 Renderer"
    new "Forçar Renderizador GL2"
    old "Force ANGLE2 Renderer"
    new "Forçar Renderizador ANGLE2"
    old "Force GLES2 Renderer"
    new "Forçar Renderizador GLES2"
    old "Enable (No Blocklist)"
    new "Habilitar (Sem Lista de Bloqueio)"
    old "Powersave"
    new "Economia de Energia"
    old "Framerate"
    new "Taxa de Quadros"
    old "Screen"
    new "Máximo Suportado pela Tela"
    old "60"
    new "60"
    old "30"
    new "30"
    old "Tearing"
    new "Tearing"
    old "Changes will take effect the next time this program is run."
    new "As alterações serão aplicadas na próxima vez que este jogo for executado."
    old "Quit"
    new "Sair"
    old "Performance Warning"
    new "Aviso de Performance"
    old "This computer is using software rendering."
    new "Este dispositivo está usando renderização via software."
    old "This game requires use of GL2 that can't be initialised."
    new "Este jogo requer o uso de GL2, que não pode ser inicializado."
    old "This computer has a problem displaying graphics: [problem]."
    new "Este dispositivo está com um problema na exibição de gráficos: [problem]."
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display."
    new "Os drivers gráficos podem estar desatualizados ou sem funcionar direito. Isso pode causar lentidão ou uma exibição incorreta dos gráficos."
    old "The {a=edit:1:log.txt}log.txt{/a} file may contain information to help you determine what is wrong with your computer."
    new "O arquivo {a=edit:1:log.txt}log.txt{/a} pode conter informações que ajudarão a determinar o que há de errado com seu dispositivo."
    old "More details on how to fix this can be found in the {a=[url]}documentation{/a}."
    new "Mais detalhes sobre como corrigir isso podem ser encontrados na {a=[url]}documentação{/a}."
    old "Continue, Show this warning again"
    new "Continuar, Mostrar este aviso novamente"
    old "Continue, Don't show warning again"
    new "Continuar, Não mostrar este aviso novamente"
    old "Change render options"
    new "Alterar opções de renderização"
    old "Select Gamepad to Calibrate"
    new "Selecione o Controle para Calibrar"
    old "No Gamepads Available"
    new "Não há Controles Disponíveis"
    old "Calibrating [name] ([i]/[total])"
    new "Calibrando [name] ([i]/[total])"
    old "Press or move the '[control!s]' [kind]."
    new "Pressione ou movimente os [kind] '[control!s]'"
    old "Skip (A)"
    new "Pular (A)"
    old "Back (B)"
    new "Voltar (B)"
    old "Open"
    new "Abrir"
    old "Opens the traceback.txt file in a text editor."
    new "Abre o arquivo traceback.txt em um editor de texto."
    old "Copy BBCode"
    new "Copiar BBCode"
    old "Copies the traceback.txt file to the clipboard as BBcode for forums like https://lemmasoft.renai.us/."
    new "Copia o arquivo traceback.txt para a área de transferência como BBcode para fóruns como https://lemmasoft.renai.us/."
    old "Copy Markdown"
    new "Copiar Markdown"
    old "Copies the traceback.txt file to the clipboard as Markdown for Discord."
    new "Copia o arquivo traceback.txt para a área de transferência como Markdown para o Discord."
    old "An exception has occurred."
    new "Ocorreu uma exceção."
    old "Rollback"
    new "Rollback"
    old "Attempts a roll back to a prior time, allowing you to save or choose a different choice."
    new "Tenta dar rollback para um momento anterior, permitindo que você salve ou faça uma escolha diferente."
    old "Ignore"
    new "Ignorar"
    old "Ignores the exception, allowing you to continue."
    new "Ignora a exceção, permitindo que você continue."
    old "Ignores the exception, allowing you to continue. This often leads to additional errors."
    new "Ignora a exceção, permitindo que você continue. Isso costuma causar erros adicionais."
    old "Reload"
    new "Recarregar"
    old "Reloads the game from disk, saving and restoring game state if possible."
    new "Recarrega os arquivos do jogo do armazenamento, salvando e restaurando o estado do jogo se possível."
    old "Console"
    new "Console"
    old "Opens a console to allow debugging the problem."
    new "Abre um console para permitir depurar o problema."
    old "Quits the game."
    new "Fecha o jogo."
    old "Parsing the script failed."
    new "A interpretação do script falhou."
    old "Back"
    new "Voltar"
    old "History"
    new "Compêndio"
    old "Skip"
    new "Pular"
    old "Auto"
    new "Modo Auto"
    old "Save"
    new "Salvar"
    old "Q.Save"
    new "Salvar Rápido"
    old "Q.Load"
    new "Carregar Rápido"
    old "Prefs"
    new "Preferências"
    old "Patreon"
    new "Patreon"
    old "Let us Begin"
    new "Vamos Começar"
    old "The Compendium"
    new "Compêndio"
    old "Save?"
    new "Quer Salvar?"
    old "Album WIP"
    new "Álbum (WIP)"
    old "Load from Save"
    new "Carregar Save"
    old "Preferences"
    new "Preferências"
    old "SubscribeStar"
    new "SubscribeStar"
    old "End Replay"
    new "Encerrar Replay"
    old "Main Menu"
    new "Menu Principal"
    old "Info and Credits"
    new "Infos e Créditos"
    old "Help!"
    new "Ajuda!"
    old "See ya soon"
    new "Até logo"
    old "Return"
    new "Voltar"
    old "About"
    new "Sobre"
    old "Version [config.version!t]\n"
    new "Versão [config.version!t]\n"
    old "Made with {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\n[renpy.license!t]"
    new "Feito com {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\n[renpy.license!t]"
    old "If you found this, I hope you had a great day and this game brought you smiles and laughs. That was the point of making this!"
    new "Se você encontrou isso, eu espero que você tenha tido um ótimo dia e que este jogo te cause risos e gargalhadas. Este é o objetivo ao fazer isso aqui!"
    old "Load"
    new "Carregar"
    old "Page {}"
    new "Página {}"
    old "Automatic saves"
    new "Saves automáticos"
    old "Quick saves"
    new "Saves rápidos"
    old "{#file_time}%A, %B %d %Y, %H:%M"
    new "{#file_time}%A, %d de %B de %Y, %H:%M"
    old "empty slot"
    new "slot vazio"
    old "<"
    new "<"
    old "{#auto_page}A"
    new "{#auto_page}A"
    old "{#quick_page}Q"
    new "{#quick_page}R"
    old ">"
    new ">"
    old "Display"
    new "Modo de Vídeo"
    old "Window"
    new "Janela"
    old "Fullscreen"
    new "Tela Cheia"
    old "Rollback Side"
    new "Lado de Rollback"
    old "Disable"
    new "Desabilitar"
    old "Left"
    new "Esquerda"
    old "Right"
    new "Direita"
    old "Unseen Text"
    new "Texto Não Visto"
    old "After Choices"
    new "Após Escolhas"
    old "Transitions"
    new "Transições"
    old "{size=+35}       Text{/size}"
    new "{size=+35}     Cor do {/size}"
    old "Cyan"
    new "Ciano"
    old "Yellow"
    new "Amarelo"
    old "Red"
    new "Vermelho"
    old "{size=+35}Color{/size}"
    new "{size=+35}Texto{/size}"
    old "Green"
    new "Verde"
    old "White"
    new "Branco"
    old "Violet"
    new "Violeta"
    old "{size=+35}Styling{/size}"
    new "{size=+35}Estilo{/size}"
    old "Bold On"
    new "Negrito Ligado"
    old "Bold Off"
    new "Negrito Desligado"
    old "Outlines On"
    new "Contorno Ligado"
    old "Outlines Off"
    new "Contorno Desligado"
    old "Font Size"
    new "Tamanho da Fonte"
    old "Large"
    new "Grande"
    old "Regular"
    new "Normal"
    old "Small"
    new "Pequena"
    old "Text Speed"
    new "Velocidade do Texto"
    old "Auto-Forward Time"
    new "Velocidade do Modo Auto"
    old "Music Volume"
    new "Volume das Músicas"
    old "Sound Volume"
    new "Volume dos Efeitos Sonoros"
    old "Test"
    new "Teste"
    old "Voice Volume"
    new "Volume da Voz"
    old "Mute All"
    new "Mutar Tudo"
    old "Chronicles of TMG"
    new "Crônicas de TMG"
    old "The dialogue history is empty."
    new "O histórico de diálogo está vazio."
    old "Help"
    new "Ajuda"
    old "Keyboard"
    new "Teclado"
    old "Mouse"
    new "Mouse"
    old "Gamepad"
    new "Controle"
    old "Enter"
    new "Enter"
    old "Advances dialogue and activates the interface."
    new "Avança o diálogo e ativa a interface."
    old "Space"
    new "Espaço"
    old "Advances dialogue without selecting choices."
    new "Avança o diálogo sem selecionar escolhas."
    old "Arrow Keys"
    new "Teclas Direcionais"
    old "Navigate the interface."
    new "Navegar na interface."
    old "Escape"
    new "Esc"
    old "Accesses the game menu."
    new "Acessa o menu do jogo."
    old "Ctrl"
    new "Ctrl"
    old "Skips dialogue while held down."
    new "Pula o diálogo ao manter pressionado."
    old "Tab"
    new "Tab"
    old "Toggles dialogue skipping."
    new "Liga/Desliga o pulo de diálogo."
    old "Page Up"
    new "Page Up"
    old "Rolls back to earlier dialogue."
    new "Volta para o diálogo anterior."
    old "Page Down"
    new "Page Down"
    old "Rolls forward to later dialogue."
    new "Avança para o próximo diálogo."
    old "Hides the user interface."
    new "Esconde a interface de usuário."
    old "Takes a screenshot."
    new "Tira uma captura de tela."
    old "Toggles assistive {a=https://www.renpy.org/l/voicing}self-voicing{/a}."
    new "Habilita/Desabilita a {a=https://www.renpy.org/l/voicing}narração assistiva{/a}."
    old "Opens the accessibility menu."
    new "Abre o menu de acessibilidade."
    old "Left Click"
    new "Botão esquerdo do Mouse"
    old "Middle Click"
    new "Botão do meio do Mouse"
    old "Right Click"
    new "Botão direito do Mouse"
    old "Mouse Wheel Up\nClick Rollback Side"
    new "Roda do Mouse para Cima\nClick no Lado de Rollback"
    old "Mouse Wheel Down"
    new "Roda do Mouse para Baixo"
    old "Right Trigger\nA/Bottom Button"
    new "Gatilho Direito\nA/Botão de Baixo"
    old "Left Trigger\nLeft Shoulder"
    new "Gatilho Esquerdo\nBotão Superior Esquerdo"
    old "Right Shoulder"
    new "Botão Superior Direito"
    old "D-Pad, Sticks"
    new "Direcionais, Analógicos"
    old "Start, Guide"
    new "Start, Guia"
    old "Y/Top Button"
    new "Y/Botão de Cima"
    old "Calibrate"
    new "Calibrar"
    old "Yes"
    new "Sim"
    old "No"
    new "Não"
    old "Skipping"
    new "Pulando diálogo"
    old "Menu"
    new "Menu"
    old "ProjektMOON"
    new "Projekt Moon"
    old "Some music and sound effects were provided by Zapsplat.com, through your support they got paid!\n\nThe OpenNSFW Voicepack was used for some scenes. Info can be found on their Twitter/Xitter page @OpenNSFWSP\n\nA few characters were taken, modified and used from BepisBD. Mainly the councilors in Chapter 4 and the nightmare from the beginning of Chapter 2. Some unmodified were used as background filler.\n\nExtra special thanks to TheDevian/Svengali Productions for lending me their time and helping proofread Projekt Moon! ThiccLover/JesusDev for being a great mod.\n\nDagotto for donating and also helping me with the logo you see all over! passhonQ, Dagotto, Hanako, Doc62, Nyatd, Expando and Fenn for ALL being gigachad fellow devs and supporting me!\n\nThey wanted to be anon, so thanks as well to my former proofreader as well. They know who they are and I appreciate their help. Chapter 1 wouldnt have been as smooth without them!\n\nThank you to Miracle for being my first donor! Alias, a long-time Patron AND bought my game on Itch! Wow, what a swell human!\n\n25 dollar tiers: Jeremy! Luke_aldwin (Thank you for your kind words!) *Former* Sarah! Starvessel (Great guy)! TYVM!\n\n10 dollar tier: Bonecrushboy, Commander Nathan Shepard, Castermaster, Chase Gibson, Donovan Kendall and Danielle... Substar user \"McChew\"\n\n5 dollar: Four Pieces, BACON-3, Calrak, Gloden, Leviathan, Substar User#8ceab0c4\n\n3 dollar: Rudy (thanks for alerting me about the bug!), Nyatd, Expando, Fenn, Doc62, Ysmir Farengar, Anonymous Guy, Logical Fallacy, Kuraiko, Enryu, Hanako, Michael Kopacz, Jstar6264, Crasysnake11, Ish0uldG0, mike martion, Orily (ya rly!), Patreon Love, Shadow Lykin, Stars Lord, V, Wowik, Zackery Smith, ルリ エドウ and Nagasuku!\n\nThe many chads on Subscribestar and anyone else I left out unintentionally.....\n\nMuchos gracias forever. If anyone else wants to join them or help... Please consider supporting me on Patreon; SubscribeStar or donating on Itch.io. All help helps! For real! Thank you.\n\nEat tacos."
    new "Algumas músicas e efeitos sonoros foram fornecidas por ZapSplat, sendo pagas graças ao seu apoio!\n\nO pacote de vozes OpenNSFW foi usado em algumas cenas. Visite o perfil do Twitter/X @OpenNSFWSP para mais informações.\n\nAlguns personagens foram pegos/modificados do website BepisBD (conselheiros no capítulo 4, o pesadelo do início do capítulo 2 e alguns não modificados usados como figurantes).\n\nAgradecimentos extra especiais para TheDevian/Svengali Productions por cederem seu tempo ajudando a revisar Projekt Moon e ThiccLover/JesusDev pela ajuda como mod.\n\nDagotto por doar e também por me me ajudar com o logo que você está vendo por ai! passhonQ, Dagotto, Hanako, Doc62, Nyatd, Expando e Fenn por serem desenvolvedores FODAS e me apoiarem!\n\nEles querem ficar anônimos, assim como meu ex-revisor, mas eles sabem quem eles são e eu agradeço muito pela ajuda. O capítulo 1 não teria ficado tão bom sem eles!\n\nMuito obrigado, Miracle, por ser a primeira pessoa a me apoiar financeiramente! Além disso, me apoia há bastante tempo no Patreon e comprou meu jogo na Itch! Uma pessoa incrível!\n\nApoiadores de 25 dólares: Jeremy! Luke_aldwin (Muito obrigado pelas palavras gentis)! Sarah (apoiou no passado)! Starvessel (cara incrível)! TYVM!\n\nApoiadores de 10 dólares: Bonecrushboy, Commander Nathan Shepard, Castermaster, Chase Gibson, Donovan Kendall e Danielle... Substar \"McChew\".\n\nApoiadores de 5 dólares: Four Pieces, BACON-3, Calrak, Gloden, Leviathan, Substar User#8ceab0c4\n\nApoiadores de 3 dólares: Rudy (Obrigado por me alertar sobre o bug!), Nyatd, Expando, Fenn, Doc62, Ysmir Farengar, Anonymous Guy, Logical Fallacy, Kuraiko, Enryu, Hanako, Michael Kopacz, Jstar6264, Crasysnake11, Ish0uldG0, mike martion, Orily (ya rly!), Patreon Love, Shadow Lykin, Stars Lord, V, Wowik, Zackery Smith, {font=defm64/m_plus_rounded_1c_bold.ttf}ルリ エドウ{/font} e Nagasuku!\n\nAs várias pessoas fodas no SubscribeStar e qualquer outra que eu tenha esquecido sem querer.\n\nAgradeço muito mesmo. Se alguém quiser se juntar a eles ou ajudar, por favor considere me apoiar no Patreon, SubscribeStar ou doando na Itch.io. Toda ajuda é realmente importante! Obrigado.\n\nComa tacos."
    old "\nPortuguese translation by {a=https://allmylinks.com/defm64}defm64{/a}.\nLicensed under {a=https://creativecommons.org/licenses/by-nc-sa/4.0/}CC BY-NC-SA 4.0{/a}.\n"
    new "\nTradução em Português criada por {a=https://allmylinks.com/defm64}defm64{/a}.\nLicenciada sob {a=https://creativecommons.org/licenses/by-nc-sa/4.0/}CC BY-NC-SA 4.0{/a}.\n\nFonte \"M PLUS Rounded 1c\" criada por Coji Morishita/M+ Fonts Project.\nLicenciada sob {a=https://openfontlicense.org/open-font-license-official-text/}SIL OFL 1.1{/a}.\n"
    old "Language"
    new "Idioma"
    old "English"
    new "English"
    old "Português"
    new "Português"
    old "Future MC"
    new "Protagonista do Futuro"
    old "Main Character"
    new "Protagonista"
    old "Kevin"
    new "Kevin"
    old "Future you??"
    new "Você do futuro??"
    old "Captain Mitsuko"
    new "Capitão Mitsuko"
    old "Commanding Officer"
    new "Oficial Comandante"
    old "Yes I am 18."
    new "Sim, eu tenho 18."
    old "No..."
    new "Não..."
    old "Have you seen the origin story already?"
    new "Você já viu a história de origem?"
    old "Skip it, already seen it. Thanks."
    new "Pode pular, eu já vi. Obrigado."
    old "Futanari"
    new "Futanari"
    old "Go to hell!"
    new "Vai para o inferno!"
    old "Fuck you (BAD ENDING!)"
    new "Vai se foder (FINAL RUIM!)"
    old "I won't let fear compromise who I am!"
    new "Eu não vou deixar o medo afetar quem eu sou!"
    old "Maybe you have a point... Renegade Shep was fun too."
    new "Talvez você tenha razão... Renegade Shep também era divertido."
    old "I don't care enough to ask you anything. I have nothing to say to you!"
    new "Eu não me importo o suficiente para te perguntar qualquer coisa. Eu não tenho nada a dizer para você!"
    old "No and thank you for the infomation"
    new "Não, e obrigado pela informação."
    old "about Projekt MOON?"
    new "Sobre Projekt Moon?"
    old "About Nora"
    new "Sobre Nora."
    old "About this ship/Nora?"
    new "Sobre esta nave/Nora?"
    old "Reluctantly agree"
    new "Concordar relutantemente."
    old "They sound like you guys. NO!"
    new "Eles soam como vocês. NÃO!"
    old "Heed her warning reluctantly."
    new "Atender ao aviso dela relutantemente."
    old "You self righteous kidnappers can go fuck yourselves! *BAD END*"
    new "Sequestradores hipócritas como vocês podem ir se foder! *FINAL RUIM*"
    old "Maybe I want you to be... (Pirate Ending WIP)"
    new "Talvez eu queira que você seja... (Final Pirata WIP)"
    old "I'm sorry, you tortured me and I will never forget that."
    new "Sinto muito, você me torturou e eu nunca vou esquecer isso."
    old "Servant [name]"
    new "Servo [name]"
    old "MC"
    new "Protagonista"
    old "NPC"
    new "NPC"
    old "Lilim the Succubus"
    new "Lilim a Succubus"
    old "Author"
    new "Autor"
    old "???"
    new "???"
    old "Mery"
    new "Mery"
    old "Queen Saki the Illustrious"
    new "Rainha Saki a Ilustre"
    old "Bandit"
    new "Bandido"
    old "Dumb Bandit"
    new "Bandido Burro"
    old "General K. Sarry"
    new "General K. Sarry"
    old "Albino"
    new "Albino"
    old "Guard"
    new "Guarda"
    old "Liara"
    new "Liara"
    old "[name] and Nora"
    new "[name] e Nora"
    old "Nora and Zorah"
    new "Nora e Zorah"
    old "I dont have anything for now."
    new "Eu não tenho nada por agora."
    old "about you?"
    new "Sobre você?"
    old "About Lilith?"
    new "Sobre Lilith?"
    old "About us?"
    new "Sobre nós?"
    old "Nora"
    new "Nora"
    old "Zorah"
    new "Zorah"
    old "Why not both?"
    new "Por que não ambos?"
    old "N-no one. I can't do this. It's not right!"
    new "N-ninguém. Eu não posso fazer isso. Não está certo!"
    old "My best friend did! Aren't I looking great?"
    new "Minha melhor amiga fez! Não estou incrível?"
    old "Someone with way more style than you, nerd."
    new "Alguém com muito mais estilo do que você, nerd."
    old "Knock them all out! (Good End lock-in)"
    new "Nocauteie todos eles! (Final Bom garantido)"
    old "Kill them all. (Conquest lock-in)"
    new "Mate todos eles. (Conquest garantido)"
    old "A cute elf companion?! Gladly!"
    new "Uma companheira elfa fofa?! Com prazer!"
    old "I guess, but you better make yourself useful!"
    new "Acho que sim, mas é bom você se fazer útil!"
    old "Thank you. You are cute yourself. I always loved elves in stories and whatever."
    new "Obrigado. Você também é fofa. Sempre adorei elfas em histórias e essas coisas."
    old "Will you stop kissing up to me? It's fucking annoying!"
    new "Você pode parar de puxar o meu saco? Isso é muito irritante!"
    old "No."
    new "Não."
    old "It's not worth the effort!"
    new "Não vale o esforço!"
    old "Tell the truth."
    new "Diga a verdade."
    old "None of your business"
    new "Não é da sua conta."
    old "Put your beef in her taco!"
    new "Coloque sua carne no taco dela!"
    old "Surprise, surprise... ANAL SURPRISE!"
    new "Surpresa, surpresa... ANAL SURPRESA!"
    old "Yes, you may."
    new "Sim, você pode."
    old "Sure, but what do you say?"
    new "Certo, mas o que você diz?"
    old "Yes it is. I help my friends."
    new "Sim, é isso. Eu ajudo meus amigos."
    old "No idea. I am not sure."
    new "Sei lá. Não tenho certeza."
    old "Yes, I do."
    new "Sim, eu faço."
    old "Hit a dick in the dick"
    new "Acerte um otário nas partes baixas."
    old "Yeah, my name is '[name]'. You stole me from my planet and ruined me. Fuck you, Bitch."
    new "Sim, meu nome é '[name]'. Você me roubou do meu planeta e me ferrou. Vai se foder, vadia."
    old "Hit a cunt in the cunt"
    new "Acerte uma piranha nas partes baixas."
    old "You want my cock, General, but instead I am gonna paint Tacraw's finest with my seed! (Bukkake ending)"
    new "Você quer o meu pau, General, mas em vez disso, vou pintar o melhor de Tacraw com a minha porra! (Final Bukkake)"
    old "Fuck this loser, he isn't worth my time! Impregnate all the girls! (Mass Pregnancy end)"
    new "Que se foda esse merda, ele não vale meu tempo! Engravidem todas elas! (Final Gravidez em Massa)"
    old "MC from the Past"
    new "Protagonista vindo do Passado"
    old "?????"
    new "?????"
    old "Arthur the Author"
    new "Arthur o Autor"
    old "Unknown"
    new "Desconhecido"
    old "Evil [name]"
    new "[name] do Mal"
    old "Asia"
    new "Asia"
    old "Lilith"
    new "Lilith"
    old "Everyone"
    new "Todo Mundo"
    old "Orc Soldier"
    new "Soldado Orc"
    old "Goblin Soldier"
    new "Soldado Goblin"
    old "Clarie the Wise"
    new "Clarie a Sábia"
    old "Lash the Eye Renderer"
    new "Lash o Criador de Olhos"
    old "[name] about 100 years into the future."
    new "[name] cerca de 100 anos no futuro."
    old "Skully"
    new "Skully"
    old "Fairuza"
    new "Fairuza"
    old "Ancient Drow"
    new "Drow Antigo"
    old "Nevermind."
    new "Deixa pra lá."
    old "Though, I would love to collar you and ensure you are my submissive, openly and publicly."
    new "Embora, eu adoraria te colocar uma coleira e garantir que você fosse minha submissa, de forma aberta e pública."
    old "Sex. I want to fill your womb. (Lots of creampies!)"
    new "Sexo. Eu quero encher o seu útero. (Muitas gozadas dentro!)"
    old "I want you to rethink your whole approach to rule, I will help you as a friend!"
    new "Quero que você repense toda a sua maneira de governar, vou te ajudar com isso!"
    old "Perhaps we can revise our agreement so we both don't feel left out."
    new "Talvez possamos revisar nosso acordo para que ninguém se sinta negligenciado."
    old "You need to respect my agency and destroy that contract!"
    new "Você tem que respeitar minha autonomia e destruir aquele contrato!"
    old "Fuck off."
    new "Não fode."
    old "You should! *Netori Warning!"
    new "Você deveria! (*Alerta de Netori!*)"
    old "Maybe you are right..."
    new "Talvez você esteja certa..."
    old "Hold Mery's hand to support her"
    new "Segure a mão de Mery para apoiá-la."
    old "Do nothing."
    new "Não faça nada."
    old "Find a private spot for Demonic quickie to seal your deal with her"
    new "Encontre um lugar reservado para dar uma rapidinha demoníaca para selar seu acordo com ela."
    old "Shake Lilith's hand, but nothing more..."
    new "Aperte a mão de Lilith, mas nada mais..."
    old "Peace, please??"
    new "Paz, por favor??"
    old "It's a fight."
    new "É uma briga."
    old "Liara will want to interrogate you."
    new "Liara vai querer te interrogar."
    old "I think apprehending you myself will be better!"
    new "Acho que capturar você pessoalmente será melhor!"
    old "Knockout Mitsuko"
    new "Nocauteie Mitsuko."
    old "Heal Mitsuko"
    new "Cure Mitsuko."
    old "All knowledge means self-knowledge. (Unlock the possibilities!)"
    new ""
    old "The less effort, the faster and more powerful you will be! (Mind Control!)"
    new ""
    old "But what else can you give me??"
    new ""
    old "None, I will never stop. I love torturing you and reminding you that Lilim was right."
    new ""
    old "YOUR BODY! *Netori Warning!"
    new ""
    old "Betray Tacraw, join forces with the Orcs and Goblins"
    new ""
    old "Orc lawndart!"
    new ""
    old "It's killing time, baby."
    new ""
    old "Rot in hell then."
    new ""
    old "I think apprehending you will be better!"
    new ""
    old "Let Mitsuko live"
    new ""
    old "Kill Mitsuko"
    new ""
    old "Lucy"
    new ""
    old "Eliza"
    new ""
    old "Kelly"
    new ""
    old "Possessed Red"
    new ""
    old "Asia, Creator of all the things!"
    new ""
    old "Grand Duchess Shoko"
    new ""
    old "Mya, The Jungle Councilor"
    new ""
    old "Athena, the Centaur Councilor"
    new ""
    old "Bunny, the Rabbit Councilor"
    new ""
    old "Machiko, the Kitsune Tribal Chief"
    new ""
    old "Sissy Kay Sarry"
    new ""
    old "To find the albino! I wanted to talk to and maybe help that cute kitty!"
    new ""
    old "I went to look around the prison. Curiousity killed the cat, pun intended because I found part of my past there."
    new ""
    old "I looked around the palace, I was curious about it!"
    new ""
    old "Nowhere, I am tired and want to go home."
    new ""
    old "I was maid for this... (Maid choice)"
    new ""
    old "Collar me, mistress. (Indentured Servant Choice)"
    new ""
    old "What to do with Kelly?"
    new ""
    old "Forgive her, but she is your girlfriend. Let's correct two wrongs!"
    new ""
    old "Forgive her, besties again! Like 2009 again, Fergie and Will.I.Am!"
    new ""
    old "If you really want to die..."
    new ""
    old "I guess."
    new ""
    old "Not really."
    new ""
    old "No and I am tired of it!"
    new ""
    old "What should the deposed General's fate be?"
    new ""
    old "Former General Sarry can go away with you. (You dont want Futa on Male!)"
    new ""
    old "Kay Sarry will serve me in humiliation from now on!"
    new ""
    old "General, that ass is MINE!"
    new ""
    old "Yeah, totally sure! I have already played this content and replaying it is kinda pointless! (Spoilers, perhaps)"
    new ""
    old "I made my choices for each branch and am ready to advance, thanks!"
    new ""
    old "You are right, I should enjoy things and fun is good."
    new ""
    old "Are you sure you want this or do you want to make your own choices again?"
    new ""
    old "Skip, I'm fine with the predone choices!"
    new ""
    old "No, I think I will do things myself thanks!"
    new ""
    old "Will you heed the words of a god?"
    new ""
    old "No LOL"
    new ""
    old "YES!"
    new ""
    old "No!"
    new ""
    old "To find the albino! I wanted to fuck a baby into that cute kitty!"
    new ""
    old "I looked around the palace for trouble to cause!"
    new ""
    old "I went to look around the prison to prove I am the alpha dog in the yard, but I found dogshit instead."
    new ""
    old "Nowhere, I am tired and want to go home. (ADVANCE)"
    new ""
    old "Gonna tell you off!"
    new ""
    old "I choose violence."
    new ""
    old "Sigh, no worth the energy!"
    new ""
    old "Former General Sarry can go away with you."
    new ""
    old "General, that ass is MINE! (Futa on Male path!)"
    new ""
    old "'Forgive her', but she is your girlfriend. Perfect opportunity to gaslight her over it!"
    new ""
    old "Forgive her, 'friends' yea... "
    new ""
    old "I made my choices for each already and I am ready to advance."
    new ""
    old "Yeah, I am moving on now. Bye!"
    new ""
    old "Fuck you, I am the god of Tacraw! Not you, Asia!"
    new ""
    old "Strange Yellow creature"
    new ""
    old "The thread of prophecy has been severed, do you wish to return to restore the weave of fate or persist in the doomed world you have created?"
    new ""
