translate portuguese strings:
    old "Self-voicing disabled."
    new "Narração assistiva desabilitada."
    old "Clipboard voicing enabled. "
    new "Narração da área de transferência habilitada. "
    old "Self-voicing enabled. "
    new "Narração assistiva habilitada. "
    old "bar"
    new "barra"
    old "selected"
    new "selecionado"
    old "viewport"
    new "área de visualização"
    old "horizontal scroll"
    new "rolagem horizontal"
    old "vertical scroll"
    new "rolagem vertical"
    old "activate"
    new "ativar"
    old "deactivate"
    new "desativar"
    old "increase"
    new "aumentar"
    old "decrease"
    new "diminuir"
    old "Font Override"
    new "Substituição de Fonte"
    old "Default"
    new "Padrão"
    old "DejaVu Sans"
    new "DejaVu Sans"
    old "Opendyslexic"
    new "Opendyslexic"
    old "Text Size Scaling"
    new "Escala do Tamanho do Texto"
    old "Reset"
    new "Resetar"
    old "Line Spacing Scaling"
    new "Escala do Espaçamento entre Linhas"
    old "High Contrast Text"
    new "Texto de Alto Contraste"
    old "Enable"
    new "Habilitar"
    old "Self-Voicing"
    new "Narração Assistiva"
    old "Off"
    new "Desabilitado"
    old "Text-to-speech"
    new "Texto para Fala"
    old "Clipboard"
    new "Área de Transferência"
    old "Debug"
    new "Depurar"
    old "Self-Voicing Volume Drop"
    new "Redução de Volume da Narração Assistiva"
    old "The options on this menu are intended to improve accessibility. They may not work with all games, and some combinations of options may render the game unplayable. This is not an issue with the game or engine. For the best results when changing fonts, try to keep the text size the same as it originally was."
    new "As opções nesse menu visam melhorar a accessibilidade. Elas não vão funcionar com todos os jogos, e algumas combinações de opções podem deixar o game injogável. Isso não é um problema com o jogo ou a engine. Para melhores resultados mudando fontes, tente manter o tamanho do texto igual ao que era originalmente."
    old "{#weekday}Monday"
    new "{#weekday}Segunda"
    old "{#weekday}Tuesday"
    new "{#weekday}Terça"
    old "{#weekday}Wednesday"
    new "{#weekday}Quarta"
    old "{#weekday}Thursday"
    new "{#weekday}Quinta"
    old "{#weekday}Friday"
    new "{#weekday}Sexta"
    old "{#weekday}Saturday"
    new "{#weekday}Sábado"
    old "{#weekday}Sunday"
    new "{#weekday}Domingo"
    old "{#weekday_short}Mon"
    new "{#weekday_short}Seg"
    old "{#weekday_short}Tue"
    new "{#weekday_short}Ter"
    old "{#weekday_short}Wed"
    new "{#weekday_short}Qua"
    old "{#weekday_short}Thu"
    new "{#weekday_short}Qui"
    old "{#weekday_short}Fri"
    new "{#weekday_short}Sex"
    old "{#weekday_short}Sat"
    new "{#weekday_short}Sáb"
    old "{#weekday_short}Sun"
    new "{#weekday_short}Dom"
    old "{#month}January"
    new "{#month}Janeiro"
    old "{#month}February"
    new "{#month}Fevereiro"
    old "{#month}March"
    new "{#month}Março"
    old "{#month}April"
    new "{#month}Abril"
    old "{#month}May"
    new "{#month}Maio"
    old "{#month}June"
    new "{#month}Junho"
    old "{#month}July"
    new "{#month}Julho"
    old "{#month}August"
    new "{#month}Agosto"
    old "{#month}September"
    new "{#month}Setembro"
    old "{#month}October"
    new "{#month}Outubro"
    old "{#month}November"
    new "{#month}Novembro"
    old "{#month}December"
    new "{#month}Dezembro"
    old "{#month_short}Jan"
    new "{#month_short}Jan"
    old "{#month_short}Feb"
    new "{#month_short}Fev"
    old "{#month_short}Mar"
    new "{#month_short}Mar"
    old "{#month_short}Apr"
    new "{#month_short}Abr"
    old "{#month_short}May"
    new "{#month_short}Mai"
    old "{#month_short}Jun"
    new "{#month_short}Jun"
    old "{#month_short}Jul"
    new "{#month_short}Jul"
    old "{#month_short}Aug"
    new "{#month_short}Ago"
    old "{#month_short}Sep"
    new "{#month_short}Set"
    old "{#month_short}Oct"
    new "{#month_short}Out"
    old "{#month_short}Nov"
    new "{#month_short}Nov"
    old "{#month_short}Dec"
    new "{#month_short}Dez"
    old "%b %d, %H:%M"
    new "%d %b, %H:%M"
    old "Save slot %s: [text]"
    new "Salvar no slot %s: [text]"
    old "Load slot %s: [text]"
    new "Carregar slot %s: [text]"
    old "Delete slot [text]"
    new "Deletar slot [text]"
    old "File page auto"
    new "Página do arquivo (s. auto)"
    old "File page quick"
    new "Página do arquivo (s. rápido)"
    old "File page [text]"
    new "Página [text] do arquivo"
    old "Next file page."
    new "Página seguinte do arquivo."
    old "Previous file page."
    new "Página anterior do arquivo."
    old "Quick save complete."
    new "Salvamento rápido concluído."
    old "Quick save."
    new "Salvamento rápido."
    old "Quick load."
    new "Carregamento rápido."
    old "Language [text]"
    new "Idioma [text]"
    old "Open [text] directory."
    new "Abrir diretório [text]."
    old "The interactive director is not enabled here."
    new "O diretor interativo não está habilitado aqui."
    old "⬆"
    new "⬆"
    old "⬇"
    new "⬇"
    old "Done"
    new "Feito"
    old "(statement)"
    new "(declaração)"
    old "(tag)"
    new "(tag)"
    old "(attributes)"
    new "(atributos)"
    old "(transform)"
    new "(transformação)"
    old "(transition)"
    new "(transição)"
    old "(channel)"
    new "(canal)"
    old "(filename)"
    new "(nome do arquivo)"
    old "Change"
    new "Mudar"
    old "Add"
    new "Adicionar"
    old "Cancel"
    new "Cancelar"
    old "Remove"
    new "Remover"
    old "Statement:"
    new "Declaração:"
    old "Tag:"
    new "Tag:"
    old "Attributes:"
    new "Atributos:"
    old "Click to toggle attribute, right click to toggle negative attribute."
    new "Clique para ativar/desativar o atributo, clique com botão direito para ativar/desativar o atributo negativo."
    old "Transforms:"
    new "Transformações:"
    old "Click to set transform, right click to add to transform list."
    new "Clique para definir transformação, clique com botão direito para adicionar à lista de transformações."
    old "Behind:"
    new "Segundo Plano:"
    old "Click to set, right click to add to behind list."
    new "Clique para definir, clique com botão direito para adicionar à lista de segundo plano."
    old "Transition:"
    new "Transição:"
    old "Channel:"
    new "Canal:"
    old "Audio Filename:"
    new "Nome do Arquivo de Áudio:"
    old "Are you sure?"
    new "Você tem certeza?"
    old "Are you sure you want to delete this save?"
    new "Você tem certeza que deseja deletar este save?"
    old "Are you sure you want to overwrite your save?"
    new "Você tem certeza que deseja sobrescrever este save?"
    old "Loading will lose unsaved progress.\nAre you sure you want to do this?"
    new "Ao carregar, qualquer progresso não salvo será perdido.\nVocê tem certeza que deseja fazer isso?"
    old "Are you sure you want to quit?"
    new "Você tem certeza que deseja sair?"
    old "Are you sure you want to return to the main menu?\nThis will lose unsaved progress."
    new "Você tem certeza que deseja voltar para o menu principal?\nQualquer progresso não salvo será perdido."
    old "Are you sure you want to end the replay?"
    new "Você tem certeza que deseja encerrar o replay?"
    old "Are you sure you want to begin skipping?"
    new "Você tem certeza que deseja começar a pular o diálogo?"
    old "Are you sure you want to skip to the next choice?"
    new "Você tem certeza que deseja pular o diálogo até a próxima escolha?"
    old "Are you sure you want to skip unseen dialogue to the next choice?"
    new "Você tem certeza que deseja pular o diálogo ainda não visto até a próxima escolha?"
    old "This save was created on a different device. Maliciously constructed save files can harm your computer. Do you trust this save's creator and everyone who could have changed the file?"
    new "Este save foi criado em um outro dispositivo. Arquivos de save maliciosos podem colocar seu computador em risco. O criador do save e qualquer um que tenha modificado este arquivo são confiáveis?"
    old "Do you trust the device the save was created on? You should only choose yes if you are the device's sole user."
    new "O dispositivo que criou o save é confiável? Só escolha sim se você for o único usuário deste dispositivo."
    old "Failed to save screenshot as %s."
    new "Falha ao salvar captura de tela como %s."
    old "Saved screenshot as %s."
    new "Captura de tela salva como %s."
    old "Skip Mode"
    new "Modo de Pulo de Diálogo"
    old "This program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license}here{/a}."
    new "Este programa contém software livre sob diferentes licenças, incluindo a Licença MIT e a GNU LGPL. A lista completa dos softwares, incluindo links para o código fonte completo, pode ser encontrado {a=https://www.renpy.org/l/license}aqui{/a}."
    old "display"
    new ""
    old "transitions"
    new ""
    old "skip transitions"
    new ""
    old "video sprites"
    new ""
    old "show empty window"
    new ""
    old "text speed"
    new ""
    old "joystick"
    new ""
    old "joystick..."
    new ""
    old "skip"
    new ""
    old "skip unseen [text]"
    new ""
    old "skip unseen text"
    new ""
    old "begin skipping"
    new ""
    old "after choices"
    new ""
    old "skip after choices"
    new ""
    old "auto-forward time"
    new ""
    old "auto-forward"
    new ""
    old "Auto forward"
    new ""
    old "auto-forward after click"
    new ""
    old "automatic move"
    new ""
    old "wait for voice"
    new ""
    old "voice sustain"
    new ""
    old "self voicing"
    new ""
    old "self voicing volume drop"
    new ""
    old "clipboard voicing"
    new ""
    old "debug voicing"
    new ""
    old "emphasize audio"
    new ""
    old "rollback side"
    new ""
    old "gl powersave"
    new ""
    old "gl framerate"
    new ""
    old "gl tearing"
    new ""
    old "font transform"
    new ""
    old "font size"
    new ""
    old "font line spacing"
    new ""
    old "system cursor"
    new ""
    old "renderer menu"
    new ""
    old "accessibility menu"
    new ""
    old "high contrast text"
    new ""
    old "audio when minimized"
    new ""
    old "audio when unfocused"
    new ""
    old "web cache preload"
    new ""
    old "voice after game menu"
    new ""
    old "main volume"
    new ""
    old "music volume"
    new ""
    old "sound volume"
    new ""
    old "voice volume"
    new ""
    old "mute main"
    new ""
    old "mute music"
    new ""
    old "mute sound"
    new ""
    old "mute voice"
    new ""
    old "mute all"
    new ""
    old "Clipboard voicing enabled. Press 'shift+C' to disable."
    new ""
    old "Self-voicing would say \"[renpy.display.tts.last]\". Press 'alt+shift+V' to disable."
    new ""
    old "Self-voicing enabled. Press 'v' to disable."
    new ""
    old "Speech Bubble Editor"
    new ""
    old "(hide)"
    new ""
    old "Sync downloaded."
    new ""
    old "Could not connect to the Ren'Py Sync server."
    new ""
    old "The Ren'Py Sync server timed out."
    new ""
    old "An unknown error occurred while connecting to the Ren'Py Sync server."
    new ""
    old "The Ren'Py Sync server does not have a copy of this sync. The sync ID may be invalid, or it may have timed out."
    new ""
    old "Please enter the sync ID you generated.\nNever enter a sync ID you didn't create yourself."
    new ""
    old "The sync ID is not in the correct format."
    new ""
    old "The sync could not be decrypted."
    new ""
    old "The sync belongs to a different game."
    new ""
    old "The sync contains a file with an invalid name."
    new ""
    old "This will upload your saves to the {a=https://sync.renpy.org}Ren'Py Sync Server{/a}.\nDo you want to continue?"
    new ""
    old "Enter Sync ID"
    new ""
    old "This will contact the {a=https://sync.renpy.org}Ren'Py Sync Server{/a}."
    new ""
    old "Sync Success"
    new ""
    old "The Sync ID is:"
    new ""
    old "You can use this ID to download your save on another device.\nThis sync will expire in an hour.\nRen'Py Sync is supported by {a=https://www.renpy.org/sponsors.html}Ren'Py's Sponsors{/a}."
    new ""
    old "Continue"
    new ""
    old "Sync Error"
    new ""
    old "Contacting App Store\nPlease Wait..."
    new ""
    old "The Ren'Py Updater is not supported on mobile devices."
    new ""
    old "An error is being simulated."
    new ""
    old "Either this project does not support updating, or the update status file was deleted."
    new ""
    old "This account does not have permission to perform an update."
    new ""
    old "This account does not have permission to write the update log."
    new ""
    old "Could not verify update signature."
    new ""
    old "The update file was not downloaded."
    new ""
    old "The update file does not have the correct digest - it may have been corrupted."
    new ""
    old "While unpacking {}, unknown type {}."
    new ""
    old "Updater"
    new ""
    old "An error has occured:"
    new ""
    old "Checking for updates."
    new ""
    old "This program is up to date."
    new ""
    old "[u.version] is available. Do you want to install it?"
    new ""
    old "Preparing to download the updates."
    new ""
    old "Downloading the updates."
    new ""
    old "Unpacking the updates."
    new ""
    old "Finishing up."
    new ""
    old "The updates have been installed. The program will restart."
    new ""
    old "The updates have been installed."
    new ""
    old "The updates were cancelled."
    new ""
    old "Proceed"
    new ""
    old "Image [index] of [count] locked."
    new ""
    old "prev"
    new ""
    old "next"
    new ""
    old "slideshow"
    new ""
    old "return"
    new ""
    old "Renderer"
    new ""
    old "Automatically Choose"
    new ""
    old "Force GL Renderer"
    new ""
    old "Force ANGLE Renderer"
    new ""
    old "Force GLES Renderer"
    new ""
    old "Force GL2 Renderer"
    new ""
    old "Force ANGLE2 Renderer"
    new ""
    old "Force GLES2 Renderer"
    new ""
    old "Enable (No Blocklist)"
    new ""
    old "Powersave"
    new ""
    old "Framerate"
    new ""
    old "Screen"
    new ""
    old "60"
    new ""
    old "30"
    new ""
    old "Tearing"
    new ""
    old "Changes will take effect the next time this program is run."
    new ""
    old "Quit"
    new ""
    old "Performance Warning"
    new ""
    old "This computer is using software rendering."
    new ""
    old "This game requires use of GL2 that can't be initialised."
    new ""
    old "This computer has a problem displaying graphics: [problem]."
    new ""
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display."
    new ""
    old "The {a=edit:1:log.txt}log.txt{/a} file may contain information to help you determine what is wrong with your computer."
    new ""
    old "More details on how to fix this can be found in the {a=[url]}documentation{/a}."
    new ""
    old "Continue, Show this warning again"
    new ""
    old "Continue, Don't show warning again"
    new ""
    old "Change render options"
    new ""
    old "Select Gamepad to Calibrate"
    new ""
    old "No Gamepads Available"
    new ""
    old "Calibrating [name] ([i]/[total])"
    new ""
    old "Press or move the '[control!s]' [kind]."
    new ""
    old "Skip (A)"
    new ""
    old "Back (B)"
    new ""
    old "Open"
    new ""
    old "Opens the traceback.txt file in a text editor."
    new ""
    old "Copy BBCode"
    new ""
    old "Copies the traceback.txt file to the clipboard as BBcode for forums like https://lemmasoft.renai.us/."
    new ""
    old "Copy Markdown"
    new ""
    old "Copies the traceback.txt file to the clipboard as Markdown for Discord."
    new ""
    old "An exception has occurred."
    new ""
    old "Rollback"
    new ""
    old "Attempts a roll back to a prior time, allowing you to save or choose a different choice."
    new ""
    old "Ignore"
    new ""
    old "Ignores the exception, allowing you to continue."
    new ""
    old "Ignores the exception, allowing you to continue. This often leads to additional errors."
    new ""
    old "Reload"
    new ""
    old "Reloads the game from disk, saving and restoring game state if possible."
    new ""
    old "Console"
    new ""
    old "Opens a console to allow debugging the problem."
    new ""
    old "Quits the game."
    new ""
    old "Parsing the script failed."
    new ""
    old "Back"
    new "Voltar"
    old "History"
    new "Compêndio"
    old "Skip"
    new "Pular"
    old "Auto"
    new "Modo Auto"
    old "Save"
    new "Salvar"
    old "Q.Save"
    new "Salvar Rápido"
    old "Q.Load"
    new "Carregar Rápido"
    old "Prefs"
    new "Preferências"
    old "Patreon"
    new "Patreon"
    old "Let us Begin"
    new "Vamos Começar"
    old "The Compendium"
    new "Compêndio"
    old "Save?"
    new "Quer Salvar?"
    old "Album WIP"
    new "Álbum (WIP)"
    old "Load from Save"
    new "Carregar Save"
    old "Preferences"
    new "Preferências"
    old "SubscribeStar"
    new "SubscribeStar"
    old "End Replay"
    new "Encerrar Replay"
    old "Main Menu"
    new "Menu Principal"
    old "Info and Credits"
    new "Infos e Créditos"
    old "Help!"
    new "Ajuda!"
    old "See ya soon"
    new "Até logo"
    old "Return"
    new "Voltar"
    old "About"
    new "Sobre"
    old "Version [config.version!t]\n"
    new "Versão [config.version!t]\n"
    old "Made with {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\n[renpy.license!t]"
    new "Feito com {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\n[renpy.license!t]"
    old "If you found this, I hope you had a great day and this game brought you smiles and laughs. That was the point of making this!"
    new "Se você encontrou isso, eu espero que você tenha tido um ótimo dia e que este jogo te cause risos e gargalhadas. Este é o objetivo ao fazer isso aqui!"
    old "Load"
    new "Carregar"
    old "Page {}"
    new "Página {}"
    old "Automatic saves"
    new "Saves automáticos"
    old "Quick saves"
    new "Saves rápidos"
    old "{#file_time}%A, %B %d %Y, %H:%M"
    new "{#file_time}%A, %d %B %Y, %H:%M"
    old "empty slot"
    new "slot vazio"
    old "<"
    new "<"
    old "{#auto_page}A"
    new "{#auto_page}A"
    old "{#quick_page}Q"
    new "{#quick_page}R"
    old ">"
    new ">"
    old "Display"
    new "Modo de Vídeo"
    old "Window"
    new "Janela"
    old "Fullscreen"
    new "Tela Cheia"
    old "Rollback Side"
    new "Lado de Rollback"
    old "Disable"
    new "Desabilitar"
    old "Left"
    new "Esquerda"
    old "Right"
    new "Direita"
    old "Unseen Text"
    new "Texto Não Visto"
    old "After Choices"
    new "Após Escolhas"
    old "Transitions"
    new "Transições"
    old "{size=+35}       Text{/size}"
    new "{size=+35}     Cor do {/size}"
    old "Cyan"
    new "Ciano"
    old "Yellow"
    new "Amarelo"
    old "Red"
    new "Vermelho"
    old "{size=+35}Color{/size}"
    new "{size=+35}Texto{/size}"
    old "Green"
    new "Verde"
    old "White"
    new "Branco"
    old "Violet"
    new "Violeta"
    old "{size=+35}Styling{/size}"
    new "{size=+35}Estilo{/size}"
    old "Bold On"
    new "Negrito Ligado"
    old "Bold Off"
    new "Negrito Desligado"
    old "Outlines On"
    new "Contorno Ligado"
    old "Outlines Off"
    new "Contorno Desligado"
    old "Font Size"
    new "Tamanho da Fonte"
    old "Large"
    new "Grande"
    old "Regular"
    new "Normal"
    old "Small"
    new "Pequena"
    old "Text Speed"
    new "Velocidade do Texto"
    old "Auto-Forward Time"
    new "Velocidade do Modo Auto"
    old "Music Volume"
    new "Volume das Músicas"
    old "Sound Volume"
    new "Volume dos Efeitos Sonoros"
    old "Test"
    new "Teste"
    old "Voice Volume"
    new "Volume da Voz"
    old "Mute All"
    new "Mutar Tudo"
    old "Chronicles of TMG"
    new "Crônicas de TMG"
    old "The dialogue history is empty."
    new "O histórico de diálogo está vazio."
    old "Help"
    new "Ajuda"
    old "Keyboard"
    new "Teclado"
    old "Mouse"
    new "Mouse"
    old "Gamepad"
    new "Controle"
    old "Enter"
    new "Enter"
    old "Advances dialogue and activates the interface."
    new "Avança o diálogo e ativa a interface."
    old "Space"
    new "Espaço"
    old "Advances dialogue without selecting choices."
    new "Avança o diálogo sem selecionar escolhas."
    old "Arrow Keys"
    new "Teclas Direcionais"
    old "Navigate the interface."
    new "Navegar na interface."
    old "Escape"
    new "Esc"
    old "Accesses the game menu."
    new "Acessa o menu do jogo."
    old "Ctrl"
    new "Ctrl"
    old "Skips dialogue while held down."
    new "Pula o diálogo ao manter pressionado."
    old "Tab"
    new "Tab"
    old "Toggles dialogue skipping."
    new "Liga/Desliga o pulo de diálogo."
    old "Page Up"
    new "Page Up"
    old "Rolls back to earlier dialogue."
    new "Volta para o diálogo anterior."
    old "Page Down"
    new "Page Down"
    old "Rolls forward to later dialogue."
    new "Avança para o próximo diálogo."
    old "Hides the user interface."
    new "Esconde a interface de usuário."
    old "Takes a screenshot."
    new "Tira uma captura de tela."
    old "Toggles assistive {a=https://www.renpy.org/l/voicing}self-voicing{/a}."
    new "Habilita/Desabilita a {a=https://www.renpy.org/l/voicing}narração assistiva{/a}."
    old "Opens the accessibility menu."
    new "Abre o menu de acessibilidade."
    old "Left Click"
    new "Botão esquerdo do Mouse"
    old "Middle Click"
    new "Botão do meio do Mouse"
    old "Right Click"
    new "Botão direito do Mouse"
    old "Mouse Wheel Up\nClick Rollback Side"
    new "Roda do Mouse para Cima\nClick no Lado de Rollback"
    old "Mouse Wheel Down"
    new "Roda do Mouse para Baixo"
    old "Right Trigger\nA/Bottom Button"
    new "Gatilho Direito\nA/Botão de Baixo"
    old "Left Trigger\nLeft Shoulder"
    new "Gatilho Esquerdo\nBotão Superior Esquerdo"
    old "Right Shoulder"
    new "Botão Superior Direito"
    old "D-Pad, Sticks"
    new "Direcionais, Analógicos"
    old "Start, Guide"
    new "Start, Guia"
    old "Y/Top Button"
    new "Y/Botão de Cima"
    old "Calibrate"
    new "Calibrar"
    old "Yes"
    new "Sim"
    old "No"
    new "Não"
    old "Skipping"
    new "Pulando diálogo"
    old "Menu"
    new "Menu"
    old "ProjektMOON"
    new "Projekt Moon"
    old "Some music and sound effects were provided by Zapsplat.com, through your support they got paid!\n\nThe OpenNSFW Voicepack was used for some scenes. Info can be found on their Twitter/Xitter page @OpenNSFWSP\n\nA few characters were taken, modified and used from BepisBD. Mainly the councilors in Chapter 4 and the nightmare from the beginning of Chapter 2. Some unmodified were used as background filler.\n\nExtra special thanks to TheDevian/Svengali Productions for lending me their time and helping proofread Projekt Moon! ThiccLover/JesusDev for being a great mod.\n\nDagotto for donating and also helping me with the logo you see all over! passhonQ, Dagotto, Hanako, Doc62, Nyatd, Expando and Fenn for ALL being gigachad fellow devs and supporting me!\n\nThey wanted to be anon, so thanks as well to my former proofreader as well. They know who they are and I appreciate their help. Chapter 1 wouldnt have been as smooth without them!\n\nThank you to Miracle for being my first donor! Alias, a long-time Patron AND bought my game on Itch! Wow, what a swell human!\n\n25 dollar tiers: Jeremy! Luke_aldwin (Thank you for your kind words!) *Former* Sarah! Starvessel (Great guy)! TYVM!\n\n10 dollar tier: Bonecrushboy, Commander Nathan Shepard, Castermaster, Chase Gibson, Donovan Kendall and Danielle... Substar user \"McChew\"\n\n5 dollar: Four Pieces, BACON-3, Calrak, Gloden, Leviathan, Substar User#8ceab0c4\n\n3 dollar: Rudy (thanks for alerting me about the bug!), Nyatd, Expando, Fenn, Doc62, Ysmir Farengar, Anonymous Guy, Logical Fallacy, Kuraiko, Enryu, Hanako, Michael Kopacz, Jstar6264, Crasysnake11, Ish0uldG0, mike martion, Orily (ya rly!), Patreon Love, Shadow Lykin, Stars Lord, V, Wowik, Zackery Smith, ルリ エドウ and Nagasuku!\n\nThe many chads on Subscribestar and anyone else I left out unintentionally.....\n\nMuchos gracias forever. If anyone else wants to join them or help... Please consider supporting me on Patreon; SubscribeStar or donating on Itch.io. All help helps! For real! Thank you.\n\nEat tacos."
    new "Algumas músicas e efeitos sonoros foram fornecidas por ZapSplat, sendo pagas graças ao seu apoio!\n\nO pacote de vozes OpenNSFW foi usado em algumas cenas. Visite o perfil do Twitter/X @OpenNSFWSP para mais informações.\n\nAlguns personagens foram pegos/modificados do website BepisBD (conselheiros no capítulo 4, o pesadelo do início do capítulo 2 e alguns não modificados usados como figurantes).\n\nAgradecimentos extra especiais para TheDevian/Svengali Productions por cederem seu tempo ajudando a revisar Projekt Moon e ThiccLover/JesusDev pela ajuda como mod.\n\nDagotto por doar e também por me me ajudar com o logo que você está vendo por ai! passhonQ, Dagotto, Hanako, Doc62, Nyatd, Expando e Fenn por serem desenvolvedores FODAS e me apoiarem!\n\nEles querem ficar anônimos, assim como meu ex-revisor, mas eles sabem quem eles são e eu agradeço muito pela ajuda. O capítulo 1 não teria ficado tão bom sem eles!\n\nMuito obrigado, Miracle, por ser a primeira pessoa a me apoiar financeiramente! Além disso, me apoia há bastante tempo no Patreon e comprou meu jogo na Itch! Uma pessoa incrível!\n\nApoiadores de 25 dólares: Jeremy! Luke_aldwin (Muito obrigado pelas palavras gentis)! Sarah (apoiou no passado)! Starvessel (cara incrível)! TYVM!\n\nApoiadores de 10 dólares: Bonecrushboy, Commander Nathan Shepard, Castermaster, Chase Gibson, Donovan Kendall e Danielle... Substar \"McChew\".\n\nApoiadores de 5 dólares: Four Pieces, BACON-3, Calrak, Gloden, Leviathan, Substar User#8ceab0c4\n\nApoiadores de 3 dólares: Rudy (Obrigado por me alertar sobre o bug!), Nyatd, Expando, Fenn, Doc62, Ysmir Farengar, Anonymous Guy, Logical Fallacy, Kuraiko, Enryu, Hanako, Michael Kopacz, Jstar6264, Crasysnake11, Ish0uldG0, mike martion, Orily (ya rly!), Patreon Love, Shadow Lykin, Stars Lord, V, Wowik, Zackery Smith, {font=defm64/m_plus_rounded_1c_bold.ttf}ルリ エドウ{/font} e Nagasuku!\n\nAs várias pessoas fodas no SubscribeStar e qualquer outra que eu tenha esquecido sem querer.\n\nAgradeço muito mesmo. Se alguém quiser se juntar a eles ou ajudar, por favor considere me apoiar no Patreon, SubscribeStar ou doando na Itch.io. Toda ajuda é realmente importante! Obrigado.\n\nComa tacos."
    old "\nPortuguese translation by {a=https://allmylinks.com/defm64}defm64{/a}.\nLicensed under {a=https://creativecommons.org/licenses/by-nc-sa/4.0/}CC BY-NC-SA 4.0{/a}.\n"
    new "\nTradução em Português criada por {a=https://allmylinks.com/defm64}defm64{/a}.\nLicenciada sob {a=https://creativecommons.org/licenses/by-nc-sa/4.0/}CC BY-NC-SA 4.0{/a}.\n\nFonte \"M PLUS Rounded 1c\" criada por Coji Morishita/M+ Fonts Project.\nLicenciada sob {a=https://openfontlicense.org/open-font-license-official-text/}SIL OFL 1.1{/a}.\n"
    old "Language"
    new "Idioma"
    old "English"
    new "English"
    old "Português"
    new "Português"
    old "Future MC"
    new ""
    old "Main Character"
    new ""
    old "Kevin"
    new ""
    old "Future you??"
    new ""
    old "Captain Mitsuko"
    new ""
    old "Commanding Officer"
    new ""
    old "Yes I am 18."
    new ""
    old "No..."
    new ""
    old "Have you seen the origin story already?"
    new ""
    old "Skip it, already seen it. Thanks."
    new ""
    old "Futanari"
    new ""
    old "Go to hell!"
    new ""
    old "Fuck you (BAD ENDING!)"
    new ""
    old "I won't let fear compromise who I am!"
    new ""
    old "Maybe you have a point... Renegade Shep was fun too."
    new ""
    old "I don't care enough to ask you anything. I have nothing to say to you!"
    new ""
    old "No and thank you for the infomation"
    new ""
    old "about Projekt MOON?"
    new ""
    old "About Nora"
    new ""
    old "About this ship/Nora?"
    new ""
    old "Reluctantly agree"
    new ""
    old "They sound like you guys. NO!"
    new ""
    old "Heed her warning reluctantly."
    new ""
    old "You self righteous kidnappers can go fuck yourselves! *BAD END*"
    new ""
    old "Maybe I want you to be... (Pirate Ending WIP)"
    new ""
    old "I'm sorry, you tortured me and I will never forget that."
    new ""
    old "Servant [name]"
    new ""
    old "MC"
    new ""
    old "NPC"
    new ""
    old "Lilim the Succubus"
    new ""
    old "Author"
    new ""
    old "???"
    new ""
    old "Mery"
    new ""
    old "Queen Saki the Illustrious"
    new ""
    old "Bandit"
    new ""
    old "Dumb Bandit"
    new ""
    old "General K. Sarry"
    new ""
    old "Albino"
    new ""
    old "Guard"
    new ""
    old "Liara"
    new ""
    old "[name] and Nora"
    new ""
    old "Nora and Zorah"
    new ""
    old "I dont have anything for now."
    new ""
    old "about you?"
    new ""
    old "About Lilith?"
    new ""
    old "About us?"
    new ""
    old "Nora"
    new ""
    old "Zorah"
    new ""
    old "Why not both?"
    new ""
    old "N-no one. I can't do this. It's not right!"
    new ""
    old "My best friend did! Aren't I looking great?"
    new ""
    old "Someone with way more style than you, nerd."
    new ""
    old "Knock them all out! (Good End lock-in)"
    new ""
    old "Kill them all. (Conquest lock-in)"
    new ""
    old "A cute elf companion?! Gladly!"
    new ""
    old "I guess, but you better make yourself useful!"
    new ""
    old "Thank you. You are cute yourself. I always loved elves in stories and whatever."
    new ""
    old "Will you stop kissing up to me? It's fucking annoying!"
    new ""
    old "No."
    new ""
    old "It's not worth the effort!"
    new ""
    old "Tell the truth."
    new ""
    old "None of your business"
    new ""
    old "Put your beef in her taco!"
    new ""
    old "Surprise, surprise... ANAL SURPRISE!"
    new ""
    old "Yes, you may."
    new ""
    old "Sure, but what do you say?"
    new ""
    old "Yes it is. I help my friends."
    new ""
    old "No idea. I am not sure."
    new ""
    old "Yes, I do."
    new ""
    old "Hit a dick in the dick"
    new ""
    old "Yeah, my name is '[name]'. You stole me from my planet and ruined me. Fuck you, Bitch."
    new ""
    old "Hit a cunt in the cunt"
    new ""
    old "You want my cock, General, but instead I am gonna paint Tacraw's finest with my seed! (Bukkake ending)"
    new ""
    old "Fuck this loser, he isn't worth my time! Impregnate all the girls! (Mass Pregnancy end)"
    new ""
    old "MC from the Past"
    new ""
    old "?????"
    new ""
    old "Arthur the Author"
    new ""
    old "Unknown"
    new ""
    old "Evil [name]"
    new ""
    old "Asia"
    new ""
    old "Lilith"
    new ""
    old "Everyone"
    new ""
    old "Orc Soldier"
    new ""
    old "Goblin Soldier"
    new ""
    old "Clarie the Wise"
    new ""
    old "Lash the Eye Renderer"
    new ""
    old "[name] about 100 years into the future."
    new ""
    old "Skully"
    new ""
    old "Fairuza"
    new ""
    old "Ancient Drow"
    new ""
    old "Nevermind."
    new ""
    old "Though, I would love to collar you and ensure you are my submissive, openly and publicly."
    new ""
    old "Sex. I want to fill your womb. (Lots of creampies!)"
    new ""
    old "I want you to rethink your whole approach to rule, I will help you as a friend!"
    new ""
    old "Perhaps we can revise our agreement so we both don't feel left out."
    new ""
    old "You need to respect my agency and destroy that contract!"
    new ""
    old "Fuck off."
    new ""
    old "You should! *Netori Warning!"
    new ""
    old "Maybe you are right..."
    new ""
    old "Hold Mery's hand to support her"
    new ""
    old "Do nothing."
    new ""
    old "Find a private spot for Demonic quickie to seal your deal with her"
    new ""
    old "Shake Lilith's hand, but nothing more..."
    new ""
    old "Peace, please??"
    new ""
    old "It's a fight."
    new ""
    old "Liara will want to interrogate you."
    new ""
    old "I think apprehending you myself will be better!"
    new ""
    old "Knockout Mitsuko"
    new ""
    old "Heal Mitsuko"
    new ""
    old "All knowledge means self-knowledge. (Unlock the possibilities!)"
    new ""
    old "The less effort, the faster and more powerful you will be! (Mind Control!)"
    new ""
    old "But what else can you give me??"
    new ""
    old "None, I will never stop. I love torturing you and reminding you that Lilim was right."
    new ""
    old "YOUR BODY! *Netori Warning!"
    new ""
    old "Betray Tacraw, join forces with the Orcs and Goblins"
    new ""
    old "Orc lawndart!"
    new ""
    old "It's killing time, baby."
    new ""
    old "Rot in hell then."
    new ""
    old "I think apprehending you will be better!"
    new ""
    old "Let Mitsuko live"
    new ""
    old "Kill Mitsuko"
    new ""
    old "Lucy"
    new ""
    old "Eliza"
    new ""
    old "Kelly"
    new ""
    old "Possessed Red"
    new ""
    old "Asia, Creator of all the things!"
    new ""
    old "Grand Duchess Shoko"
    new ""
    old "Mya, The Jungle Councilor"
    new ""
    old "Athena, the Centaur Councilor"
    new ""
    old "Bunny, the Rabbit Councilor"
    new ""
    old "Machiko, the Kitsune Tribal Chief"
    new ""
    old "Sissy Kay Sarry"
    new ""
    old "To find the albino! I wanted to talk to and maybe help that cute kitty!"
    new ""
    old "I went to look around the prison. Curiousity killed the cat, pun intended because I found part of my past there."
    new ""
    old "I looked around the palace, I was curious about it!"
    new ""
    old "Nowhere, I am tired and want to go home."
    new ""
    old "I was maid for this... (Maid choice)"
    new ""
    old "Collar me, mistress. (Indentured Servant Choice)"
    new ""
    old "What to do with Kelly?"
    new ""
    old "Forgive her, but she is your girlfriend. Let's correct two wrongs!"
    new ""
    old "Forgive her, besties again! Like 2009 again, Fergie and Will.I.Am!"
    new ""
    old "If you really want to die..."
    new ""
    old "I guess."
    new ""
    old "Not really."
    new ""
    old "No and I am tired of it!"
    new ""
    old "What should the deposed General's fate be?"
    new ""
    old "Former General Sarry can go away with you. (You dont want Futa on Male!)"
    new ""
    old "Kay Sarry will serve me in humiliation from now on!"
    new ""
    old "General, that ass is MINE!"
    new ""
    old "Yeah, totally sure! I have already played this content and replaying it is kinda pointless! (Spoilers, perhaps)"
    new ""
    old "I made my choices for each branch and am ready to advance, thanks!"
    new ""
    old "You are right, I should enjoy things and fun is good."
    new ""
    old "Are you sure you want this or do you want to make your own choices again?"
    new ""
    old "Skip, I'm fine with the predone choices!"
    new ""
    old "No, I think I will do things myself thanks!"
    new ""
    old "Will you heed the words of a god?"
    new ""
    old "No LOL"
    new ""
    old "YES!"
    new ""
    old "No!"
    new ""
    old "To find the albino! I wanted to fuck a baby into that cute kitty!"
    new ""
    old "I looked around the palace for trouble to cause!"
    new ""
    old "I went to look around the prison to prove I am the alpha dog in the yard, but I found dogshit instead."
    new ""
    old "Nowhere, I am tired and want to go home. (ADVANCE)"
    new ""
    old "Gonna tell you off!"
    new ""
    old "I choose violence."
    new ""
    old "Sigh, no worth the energy!"
    new ""
    old "Former General Sarry can go away with you."
    new ""
    old "General, that ass is MINE! (Futa on Male path!)"
    new ""
    old "'Forgive her', but she is your girlfriend. Perfect opportunity to gaslight her over it!"
    new ""
    old "Forgive her, 'friends' yea... "
    new ""
    old "I made my choices for each already and I am ready to advance."
    new ""
    old "Yeah, I am moving on now. Bye!"
    new ""
    old "Fuck you, I am the god of Tacraw! Not you, Asia!"
    new ""
    old "Strange Yellow creature"
    new ""
    old "The thread of prophecy has been severed, do you wish to return to restore the weave of fate or persist in the doomed world you have created?"
    new ""
