translate portuguese strings:
    old "Self-voicing disabled."
    new ""
    old "Clipboard voicing enabled. "
    new ""
    old "Self-voicing enabled. "
    new ""
    old "bar"
    new ""
    old "selected"
    new ""
    old "viewport"
    new ""
    old "horizontal scroll"
    new ""
    old "vertical scroll"
    new ""
    old "activate"
    new ""
    old "deactivate"
    new ""
    old "increase"
    new ""
    old "decrease"
    new ""
    old "Font Override"
    new ""
    old "Default"
    new ""
    old "DejaVu Sans"
    new ""
    old "Opendyslexic"
    new ""
    old "Text Size Scaling"
    new ""
    old "Reset"
    new ""
    old "Line Spacing Scaling"
    new ""
    old "High Contrast Text"
    new ""
    old "Enable"
    new ""
    old "Self-Voicing"
    new ""
    old "Off"
    new ""
    old "Text-to-speech"
    new ""
    old "Clipboard"
    new ""
    old "Debug"
    new ""
    old "Self-Voicing Volume Drop"
    new ""
    old "The options on this menu are intended to improve accessibility. They may not work with all games, and some combinations of options may render the game unplayable. This is not an issue with the game or engine. For the best results when changing fonts, try to keep the text size the same as it originally was."
    new ""
    old "{#weekday}Monday"
    new ""
    old "{#weekday}Tuesday"
    new ""
    old "{#weekday}Wednesday"
    new ""
    old "{#weekday}Thursday"
    new ""
    old "{#weekday}Friday"
    new ""
    old "{#weekday}Saturday"
    new ""
    old "{#weekday}Sunday"
    new ""
    old "{#weekday_short}Mon"
    new ""
    old "{#weekday_short}Tue"
    new ""
    old "{#weekday_short}Wed"
    new ""
    old "{#weekday_short}Thu"
    new ""
    old "{#weekday_short}Fri"
    new ""
    old "{#weekday_short}Sat"
    new ""
    old "{#weekday_short}Sun"
    new ""
    old "{#month}January"
    new ""
    old "{#month}February"
    new ""
    old "{#month}March"
    new ""
    old "{#month}April"
    new ""
    old "{#month}May"
    new ""
    old "{#month}June"
    new ""
    old "{#month}July"
    new ""
    old "{#month}August"
    new ""
    old "{#month}September"
    new ""
    old "{#month}October"
    new ""
    old "{#month}November"
    new ""
    old "{#month}December"
    new ""
    old "{#month_short}Jan"
    new ""
    old "{#month_short}Feb"
    new ""
    old "{#month_short}Mar"
    new ""
    old "{#month_short}Apr"
    new ""
    old "{#month_short}May"
    new ""
    old "{#month_short}Jun"
    new ""
    old "{#month_short}Jul"
    new ""
    old "{#month_short}Aug"
    new ""
    old "{#month_short}Sep"
    new ""
    old "{#month_short}Oct"
    new ""
    old "{#month_short}Nov"
    new ""
    old "{#month_short}Dec"
    new ""
    old "%b %d, %H:%M"
    new ""
    old "Save slot %s: [text]"
    new ""
    old "Load slot %s: [text]"
    new ""
    old "Delete slot [text]"
    new ""
    old "File page auto"
    new ""
    old "File page quick"
    new ""
    old "File page [text]"
    new ""
    old "Next file page."
    new ""
    old "Previous file page."
    new ""
    old "Quick save complete."
    new ""
    old "Quick save."
    new ""
    old "Quick load."
    new ""
    old "Language [text]"
    new ""
    old "Open [text] directory."
    new ""
    old "The interactive director is not enabled here."
    new ""
    old "⬆"
    new ""
    old "⬇"
    new ""
    old "Done"
    new ""
    old "(statement)"
    new ""
    old "(tag)"
    new ""
    old "(attributes)"
    new ""
    old "(transform)"
    new ""
    old "(transition)"
    new ""
    old "(channel)"
    new ""
    old "(filename)"
    new ""
    old "Change"
    new ""
    old "Add"
    new ""
    old "Cancel"
    new ""
    old "Remove"
    new ""
    old "Statement:"
    new ""
    old "Tag:"
    new ""
    old "Attributes:"
    new ""
    old "Click to toggle attribute, right click to toggle negative attribute."
    new ""
    old "Transforms:"
    new ""
    old "Click to set transform, right click to add to transform list."
    new ""
    old "Behind:"
    new ""
    old "Click to set, right click to add to behind list."
    new ""
    old "Transition:"
    new ""
    old "Channel:"
    new ""
    old "Audio Filename:"
    new ""
    old "Are you sure?"
    new ""
    old "Are you sure you want to delete this save?"
    new ""
    old "Are you sure you want to overwrite your save?"
    new ""
    old "Loading will lose unsaved progress.\nAre you sure you want to do this?"
    new ""
    old "Are you sure you want to quit?"
    new ""
    old "Are you sure you want to return to the main menu?\nThis will lose unsaved progress."
    new ""
    old "Are you sure you want to end the replay?"
    new ""
    old "Are you sure you want to begin skipping?"
    new ""
    old "Are you sure you want to skip to the next choice?"
    new ""
    old "Are you sure you want to skip unseen dialogue to the next choice?"
    new ""
    old "This save was created on a different device. Maliciously constructed save files can harm your computer. Do you trust this save's creator and everyone who could have changed the file?"
    new ""
    old "Do you trust the device the save was created on? You should only choose yes if you are the device's sole user."
    new ""
    old "Failed to save screenshot as %s."
    new ""
    old "Saved screenshot as %s."
    new ""
    old "Skip Mode"
    new ""
    old "This program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license}here{/a}."
    new ""
    old "display"
    new ""
    old "transitions"
    new ""
    old "skip transitions"
    new ""
    old "video sprites"
    new ""
    old "show empty window"
    new ""
    old "text speed"
    new ""
    old "joystick"
    new ""
    old "joystick..."
    new ""
    old "skip"
    new ""
    old "skip unseen [text]"
    new ""
    old "skip unseen text"
    new ""
    old "begin skipping"
    new ""
    old "after choices"
    new ""
    old "skip after choices"
    new ""
    old "auto-forward time"
    new ""
    old "auto-forward"
    new ""
    old "Auto forward"
    new ""
    old "auto-forward after click"
    new ""
    old "automatic move"
    new ""
    old "wait for voice"
    new ""
    old "voice sustain"
    new ""
    old "self voicing"
    new ""
    old "self voicing volume drop"
    new ""
    old "clipboard voicing"
    new ""
    old "debug voicing"
    new ""
    old "emphasize audio"
    new ""
    old "rollback side"
    new ""
    old "gl powersave"
    new ""
    old "gl framerate"
    new ""
    old "gl tearing"
    new ""
    old "font transform"
    new ""
    old "font size"
    new ""
    old "font line spacing"
    new ""
    old "system cursor"
    new ""
    old "renderer menu"
    new ""
    old "accessibility menu"
    new ""
    old "high contrast text"
    new ""
    old "audio when minimized"
    new ""
    old "audio when unfocused"
    new ""
    old "web cache preload"
    new ""
    old "voice after game menu"
    new ""
    old "main volume"
    new ""
    old "music volume"
    new ""
    old "sound volume"
    new ""
    old "voice volume"
    new ""
    old "mute main"
    new ""
    old "mute music"
    new ""
    old "mute sound"
    new ""
    old "mute voice"
    new ""
    old "mute all"
    new ""
    old "Clipboard voicing enabled. Press 'shift+C' to disable."
    new ""
    old "Self-voicing would say \"[renpy.display.tts.last]\". Press 'alt+shift+V' to disable."
    new ""
    old "Self-voicing enabled. Press 'v' to disable."
    new ""
    old "Speech Bubble Editor"
    new ""
    old "(hide)"
    new ""
    old "Sync downloaded."
    new ""
    old "Could not connect to the Ren'Py Sync server."
    new ""
    old "The Ren'Py Sync server timed out."
    new ""
    old "An unknown error occurred while connecting to the Ren'Py Sync server."
    new ""
    old "The Ren'Py Sync server does not have a copy of this sync. The sync ID may be invalid, or it may have timed out."
    new ""
    old "Please enter the sync ID you generated.\nNever enter a sync ID you didn't create yourself."
    new ""
    old "The sync ID is not in the correct format."
    new ""
    old "The sync could not be decrypted."
    new ""
    old "The sync belongs to a different game."
    new ""
    old "The sync contains a file with an invalid name."
    new ""
    old "This will upload your saves to the {a=https://sync.renpy.org}Ren'Py Sync Server{/a}.\nDo you want to continue?"
    new ""
    old "Enter Sync ID"
    new ""
    old "This will contact the {a=https://sync.renpy.org}Ren'Py Sync Server{/a}."
    new ""
    old "Sync Success"
    new ""
    old "The Sync ID is:"
    new ""
    old "You can use this ID to download your save on another device.\nThis sync will expire in an hour.\nRen'Py Sync is supported by {a=https://www.renpy.org/sponsors.html}Ren'Py's Sponsors{/a}."
    new ""
    old "Continue"
    new ""
    old "Sync Error"
    new ""
    old "Contacting App Store\nPlease Wait..."
    new ""
    old "The Ren'Py Updater is not supported on mobile devices."
    new ""
    old "An error is being simulated."
    new ""
    old "Either this project does not support updating, or the update status file was deleted."
    new ""
    old "This account does not have permission to perform an update."
    new ""
    old "This account does not have permission to write the update log."
    new ""
    old "Could not verify update signature."
    new ""
    old "The update file was not downloaded."
    new ""
    old "The update file does not have the correct digest - it may have been corrupted."
    new ""
    old "While unpacking {}, unknown type {}."
    new ""
    old "Updater"
    new ""
    old "An error has occured:"
    new ""
    old "Checking for updates."
    new ""
    old "This program is up to date."
    new ""
    old "[u.version] is available. Do you want to install it?"
    new ""
    old "Preparing to download the updates."
    new ""
    old "Downloading the updates."
    new ""
    old "Unpacking the updates."
    new ""
    old "Finishing up."
    new ""
    old "The updates have been installed. The program will restart."
    new ""
    old "The updates have been installed."
    new ""
    old "The updates were cancelled."
    new ""
    old "Proceed"
    new ""
    old "Image [index] of [count] locked."
    new ""
    old "prev"
    new ""
    old "next"
    new ""
    old "slideshow"
    new ""
    old "return"
    new ""
    old "Renderer"
    new ""
    old "Automatically Choose"
    new ""
    old "Force GL Renderer"
    new ""
    old "Force ANGLE Renderer"
    new ""
    old "Force GLES Renderer"
    new ""
    old "Force GL2 Renderer"
    new ""
    old "Force ANGLE2 Renderer"
    new ""
    old "Force GLES2 Renderer"
    new ""
    old "Enable (No Blocklist)"
    new ""
    old "Powersave"
    new ""
    old "Framerate"
    new ""
    old "Screen"
    new ""
    old "60"
    new ""
    old "30"
    new ""
    old "Tearing"
    new ""
    old "Changes will take effect the next time this program is run."
    new ""
    old "Quit"
    new ""
    old "Performance Warning"
    new ""
    old "This computer is using software rendering."
    new ""
    old "This game requires use of GL2 that can't be initialised."
    new ""
    old "This computer has a problem displaying graphics: [problem]."
    new ""
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display."
    new ""
    old "The {a=edit:1:log.txt}log.txt{/a} file may contain information to help you determine what is wrong with your computer."
    new ""
    old "More details on how to fix this can be found in the {a=[url]}documentation{/a}."
    new ""
    old "Continue, Show this warning again"
    new ""
    old "Continue, Don't show warning again"
    new ""
    old "Change render options"
    new ""
    old "Select Gamepad to Calibrate"
    new ""
    old "No Gamepads Available"
    new ""
    old "Calibrating [name] ([i]/[total])"
    new ""
    old "Press or move the '[control!s]' [kind]."
    new ""
    old "Skip (A)"
    new ""
    old "Back (B)"
    new ""
    old "Open"
    new ""
    old "Opens the traceback.txt file in a text editor."
    new ""
    old "Copy BBCode"
    new ""
    old "Copies the traceback.txt file to the clipboard as BBcode for forums like https://lemmasoft.renai.us/."
    new ""
    old "Copy Markdown"
    new ""
    old "Copies the traceback.txt file to the clipboard as Markdown for Discord."
    new ""
    old "An exception has occurred."
    new ""
    old "Rollback"
    new ""
    old "Attempts a roll back to a prior time, allowing you to save or choose a different choice."
    new ""
    old "Ignore"
    new ""
    old "Ignores the exception, allowing you to continue."
    new ""
    old "Ignores the exception, allowing you to continue. This often leads to additional errors."
    new ""
    old "Reload"
    new ""
    old "Reloads the game from disk, saving and restoring game state if possible."
    new ""
    old "Console"
    new ""
    old "Opens a console to allow debugging the problem."
    new ""
    old "Quits the game."
    new ""
    old "Parsing the script failed."
    new ""
    old "Back"
    new "Voltar"
    old "History"
    new "Compêndio"
    old "Skip"
    new "Pular"
    old "Auto"
    new "Modo Auto"
    old "Save"
    new "Salvar"
    old "Q.Save"
    new "Salvar Rápido"
    old "Q.Load"
    new "Carregar Rápido"
    old "Prefs"
    new "Preferências"
    old "Patreon"
    new "Patreon"
    old "Let us Begin"
    new "Vamos Começar"
    old "The Compendium"
    new "O Compêndio"
    old "Save?"
    new "Quer Salvar?"
    old "Album WIP"
    new "Álbum (WIP)"
    old "Load from Save"
    new "Carregar Save"
    old "Preferences"
    new "Preferências"
    old "SubscribeStar"
    new "SubscribeStar"
    old "End Replay"
    new "Encerrar Replay"
    old "Main Menu"
    new "Menu Principal"
    old "Info and Credits"
    new "Infos e Créditos"
    old "Help!"
    new "Ajuda!"
    old "See ya soon"
    new "Até logo"
    old "Return"
    new "Voltar"
    old "About"
    new ""
    old "Version [config.version!t]\n"
    new ""
    old "Made with {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\n[renpy.license!t]"
    new ""
    old "If you found this, I hope you had a great day and this game brought you smiles and laughs. That was the point of making this!"
    new ""
    old "Load"
    new ""
    old "Page {}"
    new ""
    old "Automatic saves"
    new ""
    old "Quick saves"
    new ""
    old "{#file_time}%A, %B %d %Y, %H:%M"
    new ""
    old "empty slot"
    new ""
    old "<"
    new ""
    old "{#auto_page}A"
    new ""
    old "{#quick_page}Q"
    new ""
    old ">"
    new ""
    old "Display"
    new ""
    old "Window"
    new ""
    old "Fullscreen"
    new ""
    old "Rollback Side"
    new ""
    old "Disable"
    new ""
    old "Left"
    new ""
    old "Right"
    new ""
    old "Unseen Text"
    new ""
    old "After Choices"
    new ""
    old "Transitions"
    new ""
    old "{size=+35}       Text{/size}"
    new ""
    old "Cyan"
    new ""
    old "Yellow"
    new ""
    old "Red"
    new ""
    old "{size=+35}Color{/size}"
    new ""
    old "Green"
    new ""
    old "White"
    new ""
    old "Violet"
    new ""
    old "{size=+35}Styling{/size}"
    new ""
    old "Bold On"
    new ""
    old "Bold Off"
    new ""
    old "Outlines On"
    new ""
    old "Outlines Off"
    new ""
    old "Font Size"
    new ""
    old "Large"
    new ""
    old "Regular"
    new ""
    old "Small"
    new ""
    old "Text Speed"
    new ""
    old "Auto-Forward Time"
    new ""
    old "Music Volume"
    new ""
    old "Sound Volume"
    new ""
    old "Test"
    new ""
    old "Voice Volume"
    new ""
    old "Mute All"
    new ""
    old "Chronicles of TMG"
    new ""
    old "The dialogue history is empty."
    new ""
    old "Help"
    new ""
    old "Keyboard"
    new ""
    old "Mouse"
    new ""
    old "Gamepad"
    new ""
    old "Enter"
    new ""
    old "Advances dialogue and activates the interface."
    new ""
    old "Space"
    new ""
    old "Advances dialogue without selecting choices."
    new ""
    old "Arrow Keys"
    new ""
    old "Navigate the interface."
    new ""
    old "Escape"
    new ""
    old "Accesses the game menu."
    new ""
    old "Ctrl"
    new ""
    old "Skips dialogue while held down."
    new ""
    old "Tab"
    new ""
    old "Toggles dialogue skipping."
    new ""
    old "Page Up"
    new ""
    old "Rolls back to earlier dialogue."
    new ""
    old "Page Down"
    new ""
    old "Rolls forward to later dialogue."
    new ""
    old "Hides the user interface."
    new ""
    old "Takes a screenshot."
    new ""
    old "Toggles assistive {a=https://www.renpy.org/l/voicing}self-voicing{/a}."
    new ""
    old "Opens the accessibility menu."
    new ""
    old "Left Click"
    new ""
    old "Middle Click"
    new ""
    old "Right Click"
    new ""
    old "Mouse Wheel Up\nClick Rollback Side"
    new ""
    old "Mouse Wheel Down"
    new ""
    old "Right Trigger\nA/Bottom Button"
    new ""
    old "Left Trigger\nLeft Shoulder"
    new ""
    old "Right Shoulder"
    new ""
    old "D-Pad, Sticks"
    new ""
    old "Start, Guide"
    new ""
    old "Y/Top Button"
    new ""
    old "Calibrate"
    new ""
    old "Yes"
    new ""
    old "No"
    new ""
    old "Skipping"
    new ""
    old "Menu"
    new ""
    old "ProjektMOON"
    new ""
    old "Some music and sound effects were provided by Zapsplat.com, through your support they got paid!\n\nThe OpenNSFW Voicepack was used for some scenes. Info can be found on their Twitter/Xitter page @OpenNSFWSP\n\nA few characters were taken, modified and used from BepisBD. Mainly the councilors in Chapter 4 and the nightmare from the beginning of Chapter 2. Some unmodified were used as background filler.\n\nExtra special thanks to TheDevian/Svengali Productions for lending me their time and helping proofread Projekt Moon! ThiccLover/JesusDev for being a great mod.\n\nDagotto for donating and also helping me with the logo you see all over! passhonQ, Dagotto, Hanako, Doc62, Nyatd, Expando and Fenn for ALL being gigachad fellow devs and supporting me!\n\nThey wanted to be anon, so thanks as well to my former proofreader as well. They know who they are and I appreciate their help. Chapter 1 wouldnt have been as smooth without them!\n\nThank you to Miracle for being my first donor! Alias, a long-time Patron AND bought my game on Itch! Wow, what a swell human!\n\n25 dollar tiers: Jeremy! Luke_aldwin (Thank you for your kind words!) *Former* Sarah! Starvessel (Great guy)! TYVM!\n\n10 dollar tier: Bonecrushboy, Commander Nathan Shepard, Castermaster, Chase Gibson, Donovan Kendall and Danielle... Substar user \"McChew\"\n\n5 dollar: Four Pieces, BACON-3, Calrak, Gloden, Leviathan, Substar User#8ceab0c4\n\n3 dollar: Rudy (thanks for alerting me about the bug!), Nyatd, Expando, Fenn, Doc62, Ysmir Farengar, Anonymous Guy, Logical Fallacy, Kuraiko, Enryu, Hanako, Michael Kopacz, Jstar6264, Crasysnake11, Ish0uldG0, mike martion, Orily (ya rly!), Patreon Love, Shadow Lykin, Stars Lord, V, Wowik, Zackery Smith, ルリ エドウ and Nagasuku!\n\nThe many chads on Subscribestar and anyone else I left out unintentionally.....\n\nMuchos gracias forever. If anyone else wants to join them or help... Please consider supporting me on Patreon; SubscribeStar or donating on Itch.io. All help helps! For real! Thank you.\n\nEat tacos."
    new ""
    old "\nPortuguese translation by {a=https://allmylinks.com/defm64}defm64{/a}.\nLicensed under {a=https://creativecommons.org/licenses/by-nc-sa/4.0/}CC BY-NC-SA 4.0{/a}.\n"
    new ""
    old "Language"
    new ""
    old "English"
    new ""
    old "Português"
    new ""
    old "Future MC"
    new ""
    old "Main Character"
    new ""
    old "Kevin"
    new ""
    old "Future you??"
    new ""
    old "Captain Mitsuko"
    new ""
    old "Commanding Officer"
    new ""
    old "Yes I am 18."
    new ""
    old "No..."
    new ""
    old "Have you seen the origin story already?"
    new ""
    old "Skip it, already seen it. Thanks."
    new ""
    old "Futanari"
    new ""
    old "Go to hell!"
    new ""
    old "Fuck you (BAD ENDING!)"
    new ""
    old "I won't let fear compromise who I am!"
    new ""
    old "Maybe you have a point... Renegade Shep was fun too."
    new ""
    old "I don't care enough to ask you anything. I have nothing to say to you!"
    new ""
    old "No and thank you for the infomation"
    new ""
    old "about Projekt MOON?"
    new ""
    old "About Nora"
    new ""
    old "About this ship/Nora?"
    new ""
    old "Reluctantly agree"
    new ""
    old "They sound like you guys. NO!"
    new ""
    old "Heed her warning reluctantly."
    new ""
    old "You self righteous kidnappers can go fuck yourselves! *BAD END*"
    new ""
    old "Maybe I want you to be... (Pirate Ending WIP)"
    new ""
    old "I'm sorry, you tortured me and I will never forget that."
    new ""
    old "Servant [name]"
    new ""
    old "MC"
    new ""
    old "NPC"
    new ""
    old "Lilim the Succubus"
    new ""
    old "Author"
    new ""
    old "???"
    new ""
    old "Mery"
    new ""
    old "Queen Saki the Illustrious"
    new ""
    old "Bandit"
    new ""
    old "Dumb Bandit"
    new ""
    old "General K. Sarry"
    new ""
    old "Albino"
    new ""
    old "Guard"
    new ""
    old "Liara"
    new ""
    old "[name] and Nora"
    new ""
    old "Nora and Zorah"
    new ""
    old "I dont have anything for now."
    new ""
    old "about you?"
    new ""
    old "About Lilith?"
    new ""
    old "About us?"
    new ""
    old "Nora"
    new ""
    old "Zorah"
    new ""
    old "Why not both?"
    new ""
    old "N-no one. I can't do this. It's not right!"
    new ""
    old "My best friend did! Aren't I looking great?"
    new ""
    old "Someone with way more style than you, nerd."
    new ""
    old "Knock them all out! (Good End lock-in)"
    new ""
    old "Kill them all. (Conquest lock-in)"
    new ""
    old "A cute elf companion?! Gladly!"
    new ""
    old "I guess, but you better make yourself useful!"
    new ""
    old "Thank you. You are cute yourself. I always loved elves in stories and whatever."
    new ""
    old "Will you stop kissing up to me? It's fucking annoying!"
    new ""
    old "No."
    new ""
    old "It's not worth the effort!"
    new ""
    old "Tell the truth."
    new ""
    old "None of your business"
    new ""
    old "Put your beef in her taco!"
    new ""
    old "Surprise, surprise... ANAL SURPRISE!"
    new ""
    old "Yes, you may."
    new ""
    old "Sure, but what do you say?"
    new ""
    old "Yes it is. I help my friends."
    new ""
    old "No idea. I am not sure."
    new ""
    old "Yes, I do."
    new ""
    old "Hit a dick in the dick"
    new ""
    old "Yeah, my name is '[name]'. You stole me from my planet and ruined me. Fuck you, Bitch."
    new ""
    old "Hit a cunt in the cunt"
    new ""
    old "You want my cock, General, but instead I am gonna paint Tacraw's finest with my seed! (Bukkake ending)"
    new ""
    old "Fuck this loser, he isn't worth my time! Impregnate all the girls! (Mass Pregnancy end)"
    new ""
    old "MC from the Past"
    new ""
    old "?????"
    new ""
    old "Arthur the Author"
    new ""
    old "Unknown"
    new ""
    old "Evil [name]"
    new ""
    old "Asia"
    new ""
    old "Lilith"
    new ""
    old "Everyone"
    new ""
    old "Orc Soldier"
    new ""
    old "Goblin Soldier"
    new ""
    old "Clarie the Wise"
    new ""
    old "Lash the Eye Renderer"
    new ""
    old "[name] about 100 years into the future."
    new ""
    old "Skully"
    new ""
    old "Fairuza"
    new ""
    old "Ancient Drow"
    new ""
    old "Nevermind."
    new ""
    old "Though, I would love to collar you and ensure you are my submissive, openly and publicly."
    new ""
    old "Sex. I want to fill your womb. (Lots of creampies!)"
    new ""
    old "I want you to rethink your whole approach to rule, I will help you as a friend!"
    new ""
    old "Perhaps we can revise our agreement so we both don't feel left out."
    new ""
    old "You need to respect my agency and destroy that contract!"
    new ""
    old "Fuck off."
    new ""
    old "You should! *Netori Warning!"
    new ""
    old "Maybe you are right..."
    new ""
    old "Hold Mery's hand to support her"
    new ""
    old "Do nothing."
    new ""
    old "Find a private spot for Demonic quickie to seal your deal with her"
    new ""
    old "Shake Lilith's hand, but nothing more..."
    new ""
    old "Peace, please??"
    new ""
    old "It's a fight."
    new ""
    old "Liara will want to interrogate you."
    new ""
    old "I think apprehending you myself will be better!"
    new ""
    old "Knockout Mitsuko"
    new ""
    old "Heal Mitsuko"
    new ""
    old "All knowledge means self-knowledge. (Unlock the possibilities!)"
    new ""
    old "The less effort, the faster and more powerful you will be! (Mind Control!)"
    new ""
    old "But what else can you give me??"
    new ""
    old "None, I will never stop. I love torturing you and reminding you that Lilim was right."
    new ""
    old "YOUR BODY! *Netori Warning!"
    new ""
    old "Betray Tacraw, join forces with the Orcs and Goblins"
    new ""
    old "Orc lawndart!"
    new ""
    old "It's killing time, baby."
    new ""
    old "Rot in hell then."
    new ""
    old "I think apprehending you will be better!"
    new ""
    old "Let Mitsuko live"
    new ""
    old "Kill Mitsuko"
    new ""
    old "Lucy"
    new ""
    old "Eliza"
    new ""
    old "Kelly"
    new ""
    old "Possessed Red"
    new ""
    old "Asia, Creator of all the things!"
    new ""
    old "Grand Duchess Shoko"
    new ""
    old "Mya, The Jungle Councilor"
    new ""
    old "Athena, the Centaur Councilor"
    new ""
    old "Bunny, the Rabbit Councilor"
    new ""
    old "Machiko, the Kitsune Tribal Chief"
    new ""
    old "Sissy Kay Sarry"
    new ""
    old "To find the albino! I wanted to talk to and maybe help that cute kitty!"
    new ""
    old "I went to look around the prison. Curiousity killed the cat, pun intended because I found part of my past there."
    new ""
    old "I looked around the palace, I was curious about it!"
    new ""
    old "Nowhere, I am tired and want to go home."
    new ""
    old "I was maid for this... (Maid choice)"
    new ""
    old "Collar me, mistress. (Indentured Servant Choice)"
    new ""
    old "What to do with Kelly?"
    new ""
    old "Forgive her, but she is your girlfriend. Let's correct two wrongs!"
    new ""
    old "Forgive her, besties again! Like 2009 again, Fergie and Will.I.Am!"
    new ""
    old "If you really want to die..."
    new ""
    old "I guess."
    new ""
    old "Not really."
    new ""
    old "No and I am tired of it!"
    new ""
    old "What should the deposed General's fate be?"
    new ""
    old "Former General Sarry can go away with you. (You dont want Futa on Male!)"
    new ""
    old "Kay Sarry will serve me in humiliation from now on!"
    new ""
    old "General, that ass is MINE!"
    new ""
    old "Yeah, totally sure! I have already played this content and replaying it is kinda pointless! (Spoilers, perhaps)"
    new ""
    old "I made my choices for each branch and am ready to advance, thanks!"
    new ""
    old "You are right, I should enjoy things and fun is good."
    new ""
    old "Are you sure you want this or do you want to make your own choices again?"
    new ""
    old "Skip, I'm fine with the predone choices!"
    new ""
    old "No, I think I will do things myself thanks!"
    new ""
    old "Will you heed the words of a god?"
    new ""
    old "No LOL"
    new ""
    old "YES!"
    new ""
    old "No!"
    new ""
    old "To find the albino! I wanted to fuck a baby into that cute kitty!"
    new ""
    old "I looked around the palace for trouble to cause!"
    new ""
    old "I went to look around the prison to prove I am the alpha dog in the yard, but I found dogshit instead."
    new ""
    old "Nowhere, I am tired and want to go home. (ADVANCE)"
    new ""
    old "Gonna tell you off!"
    new ""
    old "I choose violence."
    new ""
    old "Sigh, no worth the energy!"
    new ""
    old "Former General Sarry can go away with you."
    new ""
    old "General, that ass is MINE! (Futa on Male path!)"
    new ""
    old "'Forgive her', but she is your girlfriend. Perfect opportunity to gaslight her over it!"
    new ""
    old "Forgive her, 'friends' yea... "
    new ""
    old "I made my choices for each already and I am ready to advance."
    new ""
    old "Yeah, I am moving on now. Bye!"
    new ""
    old "Fuck you, I am the god of Tacraw! Not you, Asia!"
    new ""
    old "Strange Yellow creature"
    new ""
    old "The thread of prophecy has been severed, do you wish to return to restore the weave of fate or persist in the doomed world you have created?"
    new ""
